// Code generated by protoc-gen-go.
// source: gs_db.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ESaveRoleType int32

const (
	ESaveRoleType_e_none       ESaveRoleType = 0
	ESaveRoleType_e_basic_info ESaveRoleType = 1
	ESaveRoleType_e_hero_info  ESaveRoleType = 2
	ESaveRoleType_e_item_info  ESaveRoleType = 3
	ESaveRoleType_e_job_info   ESaveRoleType = 4
	ESaveRoleType_e_soul_info  ESaveRoleType = 5
)

var ESaveRoleType_name = map[int32]string{
	0: "e_none",
	1: "e_basic_info",
	2: "e_hero_info",
	3: "e_item_info",
	4: "e_job_info",
	5: "e_soul_info",
}
var ESaveRoleType_value = map[string]int32{
	"e_none":       0,
	"e_basic_info": 1,
	"e_hero_info":  2,
	"e_item_info":  3,
	"e_job_info":   4,
	"e_soul_info":  5,
}

func (x ESaveRoleType) Enum() *ESaveRoleType {
	p := new(ESaveRoleType)
	*p = x
	return p
}
func (x ESaveRoleType) String() string {
	return proto.EnumName(ESaveRoleType_name, int32(x))
}
func (x *ESaveRoleType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ESaveRoleType_value, data, "ESaveRoleType")
	if err != nil {
		return err
	}
	*x = ESaveRoleType(value)
	return nil
}
func (ESaveRoleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type EGS_DB_ProtoId int32

const (
	EGS_DB_ProtoId_gs_get_role_data_req_id         EGS_DB_ProtoId = 1
	EGS_DB_ProtoId_db_role_data_ack_id             EGS_DB_ProtoId = 2
	EGS_DB_ProtoId_gs_role_leave_game_id           EGS_DB_ProtoId = 3
	EGS_DB_ProtoId_save_role_req_id                EGS_DB_ProtoId = 4
	EGS_DB_ProtoId_db_enter_game_check_role_req_id EGS_DB_ProtoId = 5
	EGS_DB_ProtoId_gs_enter_game_check_role_ack_id EGS_DB_ProtoId = 6
)

var EGS_DB_ProtoId_name = map[int32]string{
	1: "gs_get_role_data_req_id",
	2: "db_role_data_ack_id",
	3: "gs_role_leave_game_id",
	4: "save_role_req_id",
	5: "db_enter_game_check_role_req_id",
	6: "gs_enter_game_check_role_ack_id",
}
var EGS_DB_ProtoId_value = map[string]int32{
	"gs_get_role_data_req_id":         1,
	"db_role_data_ack_id":             2,
	"gs_role_leave_game_id":           3,
	"save_role_req_id":                4,
	"db_enter_game_check_role_req_id": 5,
	"gs_enter_game_check_role_ack_id": 6,
}

func (x EGS_DB_ProtoId) Enum() *EGS_DB_ProtoId {
	p := new(EGS_DB_ProtoId)
	*p = x
	return p
}
func (x EGS_DB_ProtoId) String() string {
	return proto.EnumName(EGS_DB_ProtoId_name, int32(x))
}
func (x *EGS_DB_ProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGS_DB_ProtoId_value, data, "EGS_DB_ProtoId")
	if err != nil {
		return err
	}
	*x = EGS_DB_ProtoId(value)
	return nil
}
func (EGS_DB_ProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type DbSkillData struct {
	Templateid       *uint32 `protobuf:"varint,1,req,name=templateid" json:"templateid,omitempty"`
	Level            *int32  `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Slot             *int32  `protobuf:"varint,3,req,name=slot" json:"slot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbSkillData) Reset()                    { *m = DbSkillData{} }
func (m *DbSkillData) String() string            { return proto.CompactTextString(m) }
func (*DbSkillData) ProtoMessage()               {}
func (*DbSkillData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DbSkillData) GetTemplateid() uint32 {
	if m != nil && m.Templateid != nil {
		return *m.Templateid
	}
	return 0
}

func (m *DbSkillData) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *DbSkillData) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

type DbHeroSoulData struct {
	Uuid             *uint64 `protobuf:"varint,1,req,name=uuid" json:"uuid,omitempty"`
	Slot             *int32  `protobuf:"varint,2,req,name=slot" json:"slot,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbHeroSoulData) Reset()                    { *m = DbHeroSoulData{} }
func (m *DbHeroSoulData) String() string            { return proto.CompactTextString(m) }
func (*DbHeroSoulData) ProtoMessage()               {}
func (*DbHeroSoulData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DbHeroSoulData) GetUuid() uint64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *DbHeroSoulData) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

type DbHeroData struct {
	Uuid             *uint64           `protobuf:"varint,1,req,name=uuid" json:"uuid,omitempty"`
	Templateid       *uint32           `protobuf:"varint,2,req,name=templateid" json:"templateid,omitempty"`
	Level            *int32            `protobuf:"varint,3,req,name=level" json:"level,omitempty"`
	Star             *int32            `protobuf:"varint,4,req,name=star" json:"star,omitempty"`
	Skills           []*DbSkillData    `protobuf:"bytes,5,rep,name=skills" json:"skills,omitempty"`
	SoulList         []*DbHeroSoulData `protobuf:"bytes,6,rep,name=soul_list" json:"soul_list,omitempty"`
	Awaken           *bool             `protobuf:"varint,7,req,name=awaken" json:"awaken,omitempty"`
	Exp              *int32            `protobuf:"varint,8,req,name=exp" json:"exp,omitempty"`
	AwakenAttr       []*HeroAttrValue  `protobuf:"bytes,9,rep,name=awaken_attr" json:"awaken_attr,omitempty"`
	Locked           *bool             `protobuf:"varint,10,req,name=locked" json:"locked,omitempty"`
	CreateTime       *uint32           `protobuf:"varint,11,opt,name=create_time" json:"create_time,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *DbHeroData) Reset()                    { *m = DbHeroData{} }
func (m *DbHeroData) String() string            { return proto.CompactTextString(m) }
func (*DbHeroData) ProtoMessage()               {}
func (*DbHeroData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DbHeroData) GetUuid() uint64 {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return 0
}

func (m *DbHeroData) GetTemplateid() uint32 {
	if m != nil && m.Templateid != nil {
		return *m.Templateid
	}
	return 0
}

func (m *DbHeroData) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *DbHeroData) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *DbHeroData) GetSkills() []*DbSkillData {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *DbHeroData) GetSoulList() []*DbHeroSoulData {
	if m != nil {
		return m.SoulList
	}
	return nil
}

func (m *DbHeroData) GetAwaken() bool {
	if m != nil && m.Awaken != nil {
		return *m.Awaken
	}
	return false
}

func (m *DbHeroData) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *DbHeroData) GetAwakenAttr() []*HeroAttrValue {
	if m != nil {
		return m.AwakenAttr
	}
	return nil
}

func (m *DbHeroData) GetLocked() bool {
	if m != nil && m.Locked != nil {
		return *m.Locked
	}
	return false
}

func (m *DbHeroData) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

type DbItemPacket struct {
	Items            []*ItemData `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *DbItemPacket) Reset()                    { *m = DbItemPacket{} }
func (m *DbItemPacket) String() string            { return proto.CompactTextString(m) }
func (*DbItemPacket) ProtoMessage()               {}
func (*DbItemPacket) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DbItemPacket) GetItems() []*ItemData {
	if m != nil {
		return m.Items
	}
	return nil
}

type DbJobData struct {
	JobId            *int32  `protobuf:"varint,1,opt,name=job_id" json:"job_id,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	IsReceive        *bool   `protobuf:"varint,3,opt,name=is_receive" json:"is_receive,omitempty"`
	IsLook           *bool   `protobuf:"varint,4,opt,name=is_look" json:"is_look,omitempty"`
	CurStep          *uint32 `protobuf:"varint,5,opt,name=cur_step" json:"cur_step,omitempty"`
	MaxStep          *uint32 `protobuf:"varint,6,opt,name=max_step" json:"max_step,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbJobData) Reset()                    { *m = DbJobData{} }
func (m *DbJobData) String() string            { return proto.CompactTextString(m) }
func (*DbJobData) ProtoMessage()               {}
func (*DbJobData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *DbJobData) GetJobId() int32 {
	if m != nil && m.JobId != nil {
		return *m.JobId
	}
	return 0
}

func (m *DbJobData) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DbJobData) GetIsReceive() bool {
	if m != nil && m.IsReceive != nil {
		return *m.IsReceive
	}
	return false
}

func (m *DbJobData) GetIsLook() bool {
	if m != nil && m.IsLook != nil {
		return *m.IsLook
	}
	return false
}

func (m *DbJobData) GetCurStep() uint32 {
	if m != nil && m.CurStep != nil {
		return *m.CurStep
	}
	return 0
}

func (m *DbJobData) GetMaxStep() uint32 {
	if m != nil && m.MaxStep != nil {
		return *m.MaxStep
	}
	return 0
}

type DbDropSpid struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Step             *int32 `protobuf:"varint,2,opt,name=step" json:"step,omitempty"`
	Value            *int32 `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DbDropSpid) Reset()                    { *m = DbDropSpid{} }
func (m *DbDropSpid) String() string            { return proto.CompactTextString(m) }
func (*DbDropSpid) ProtoMessage()               {}
func (*DbDropSpid) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *DbDropSpid) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DbDropSpid) GetStep() int32 {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return 0
}

func (m *DbDropSpid) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type DbEffect struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type             *int32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Type2            *int32 `protobuf:"varint,3,opt,name=type2" json:"type2,omitempty"`
	Num              *int32 `protobuf:"varint,4,opt,name=num" json:"num,omitempty"`
	Total            *int32 `protobuf:"varint,5,opt,name=total" json:"total,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DbEffect) Reset()                    { *m = DbEffect{} }
func (m *DbEffect) String() string            { return proto.CompactTextString(m) }
func (*DbEffect) ProtoMessage()               {}
func (*DbEffect) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *DbEffect) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *DbEffect) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *DbEffect) GetType2() int32 {
	if m != nil && m.Type2 != nil {
		return *m.Type2
	}
	return 0
}

func (m *DbEffect) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *DbEffect) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

type DbSoulData struct {
	Uid              *uint64     `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	TemplateId       *int32      `protobuf:"varint,2,opt,name=template_id" json:"template_id,omitempty"`
	Lv               *int32      `protobuf:"varint,3,opt,name=lv" json:"lv,omitempty"`
	Exp              *int32      `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Star             *int32      `protobuf:"varint,5,opt,name=star" json:"star,omitempty"`
	PosIndex         *int32      `protobuf:"varint,6,opt,name=pos_index" json:"pos_index,omitempty"`
	SuitType         *int32      `protobuf:"varint,7,opt,name=suit_type" json:"suit_type,omitempty"`
	HeroUid          *uint64     `protobuf:"varint,8,opt,name=hero_uid" json:"hero_uid,omitempty"`
	IsLock           *bool       `protobuf:"varint,9,opt,name=is_lock" json:"is_lock,omitempty"`
	MainEffect       []*DbEffect `protobuf:"bytes,10,rep,name=main_effect" json:"main_effect,omitempty"`
	AddEffect        []*DbEffect `protobuf:"bytes,11,rep,name=add_effect" json:"add_effect,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *DbSoulData) Reset()                    { *m = DbSoulData{} }
func (m *DbSoulData) String() string            { return proto.CompactTextString(m) }
func (*DbSoulData) ProtoMessage()               {}
func (*DbSoulData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *DbSoulData) GetUid() uint64 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *DbSoulData) GetTemplateId() int32 {
	if m != nil && m.TemplateId != nil {
		return *m.TemplateId
	}
	return 0
}

func (m *DbSoulData) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *DbSoulData) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *DbSoulData) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *DbSoulData) GetPosIndex() int32 {
	if m != nil && m.PosIndex != nil {
		return *m.PosIndex
	}
	return 0
}

func (m *DbSoulData) GetSuitType() int32 {
	if m != nil && m.SuitType != nil {
		return *m.SuitType
	}
	return 0
}

func (m *DbSoulData) GetHeroUid() uint64 {
	if m != nil && m.HeroUid != nil {
		return *m.HeroUid
	}
	return 0
}

func (m *DbSoulData) GetIsLock() bool {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return false
}

func (m *DbSoulData) GetMainEffect() []*DbEffect {
	if m != nil {
		return m.MainEffect
	}
	return nil
}

func (m *DbSoulData) GetAddEffect() []*DbEffect {
	if m != nil {
		return m.AddEffect
	}
	return nil
}

type DbRoleAllData struct {
	GateId           *uint64          `protobuf:"varint,1,opt,name=gate_id" json:"gate_id,omitempty"`
	RoleId           *uint64          `protobuf:"varint,2,opt,name=role_id" json:"role_id,omitempty"`
	RoleName         *string          `protobuf:"bytes,3,opt,name=role_name" json:"role_name,omitempty"`
	AccountId        *string          `protobuf:"bytes,4,opt,name=account_id" json:"account_id,omitempty"`
	Lastleavetime    *uint32          `protobuf:"varint,5,opt,name=lastleavetime" json:"lastleavetime,omitempty"`
	GameId           *uint64          `protobuf:"varint,6,opt,name=game_id" json:"game_id,omitempty"`
	NotifyClient     *int32           `protobuf:"varint,7,opt,name=notify_client" json:"notify_client,omitempty"`
	Lv               *int32           `protobuf:"varint,8,opt,name=lv" json:"lv,omitempty"`
	Exp              *int32           `protobuf:"varint,9,opt,name=exp" json:"exp,omitempty"`
	Sex              *int32           `protobuf:"varint,10,opt,name=sex" json:"sex,omitempty"`
	HeroList         []*DbHeroData    `protobuf:"bytes,11,rep,name=hero_list" json:"hero_list,omitempty"`
	ItemPacket       *DbItemPacket    `protobuf:"bytes,12,opt,name=item_packet" json:"item_packet,omitempty"`
	ItemPropertyInfo []*ItemProperty  `protobuf:"bytes,15,rep,name=item_property_info" json:"item_property_info,omitempty"`
	JobS             []*DbJobData     `protobuf:"bytes,16,rep,name=job_s" json:"job_s,omitempty"`
	PastSceneIdS     []int32          `protobuf:"varint,17,rep,name=past_scene_id_s" json:"past_scene_id_s,omitempty"`
	DropSpidS        []*DbDropSpid    `protobuf:"bytes,18,rep,name=drop_spid_s" json:"drop_spid_s,omitempty"`
	SoulS            []*DbSoulData    `protobuf:"bytes,19,rep,name=soul_s" json:"soul_s,omitempty"`
	PlotIds          []int32          `protobuf:"varint,20,rep,name=plot_ids" json:"plot_ids,omitempty"`
	BaseBuyData      *RoleBaseBuyData `protobuf:"bytes,21,opt,name=base_buy_data" json:"base_buy_data,omitempty"`
	IsNewPlayer      *bool            `protobuf:"varint,22,opt,name=is_new_player,def=1" json:"is_new_player,omitempty"`
	SaveType         *int32           `protobuf:"varint,23,opt,name=save_type" json:"save_type,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *DbRoleAllData) Reset()                    { *m = DbRoleAllData{} }
func (m *DbRoleAllData) String() string            { return proto.CompactTextString(m) }
func (*DbRoleAllData) ProtoMessage()               {}
func (*DbRoleAllData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

const Default_DbRoleAllData_IsNewPlayer bool = true

func (m *DbRoleAllData) GetGateId() uint64 {
	if m != nil && m.GateId != nil {
		return *m.GateId
	}
	return 0
}

func (m *DbRoleAllData) GetRoleId() uint64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *DbRoleAllData) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func (m *DbRoleAllData) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *DbRoleAllData) GetLastleavetime() uint32 {
	if m != nil && m.Lastleavetime != nil {
		return *m.Lastleavetime
	}
	return 0
}

func (m *DbRoleAllData) GetGameId() uint64 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *DbRoleAllData) GetNotifyClient() int32 {
	if m != nil && m.NotifyClient != nil {
		return *m.NotifyClient
	}
	return 0
}

func (m *DbRoleAllData) GetLv() int32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *DbRoleAllData) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *DbRoleAllData) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *DbRoleAllData) GetHeroList() []*DbHeroData {
	if m != nil {
		return m.HeroList
	}
	return nil
}

func (m *DbRoleAllData) GetItemPacket() *DbItemPacket {
	if m != nil {
		return m.ItemPacket
	}
	return nil
}

func (m *DbRoleAllData) GetItemPropertyInfo() []*ItemProperty {
	if m != nil {
		return m.ItemPropertyInfo
	}
	return nil
}

func (m *DbRoleAllData) GetJobS() []*DbJobData {
	if m != nil {
		return m.JobS
	}
	return nil
}

func (m *DbRoleAllData) GetPastSceneIdS() []int32 {
	if m != nil {
		return m.PastSceneIdS
	}
	return nil
}

func (m *DbRoleAllData) GetDropSpidS() []*DbDropSpid {
	if m != nil {
		return m.DropSpidS
	}
	return nil
}

func (m *DbRoleAllData) GetSoulS() []*DbSoulData {
	if m != nil {
		return m.SoulS
	}
	return nil
}

func (m *DbRoleAllData) GetPlotIds() []int32 {
	if m != nil {
		return m.PlotIds
	}
	return nil
}

func (m *DbRoleAllData) GetBaseBuyData() *RoleBaseBuyData {
	if m != nil {
		return m.BaseBuyData
	}
	return nil
}

func (m *DbRoleAllData) GetIsNewPlayer() bool {
	if m != nil && m.IsNewPlayer != nil {
		return *m.IsNewPlayer
	}
	return Default_DbRoleAllData_IsNewPlayer
}

func (m *DbRoleAllData) GetSaveType() int32 {
	if m != nil && m.SaveType != nil {
		return *m.SaveType
	}
	return 0
}

type DbRoleAccountData struct {
	RoleId           *uint64 `protobuf:"varint,1,req,name=role_id" json:"role_id,omitempty"`
	RoleName         *string `protobuf:"bytes,2,req,name=role_name" json:"role_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbRoleAccountData) Reset()                    { *m = DbRoleAccountData{} }
func (m *DbRoleAccountData) String() string            { return proto.CompactTextString(m) }
func (*DbRoleAccountData) ProtoMessage()               {}
func (*DbRoleAccountData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *DbRoleAccountData) GetRoleId() uint64 {
	if m != nil && m.RoleId != nil {
		return *m.RoleId
	}
	return 0
}

func (m *DbRoleAccountData) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

type GsGetRoleDataReq struct {
	Data             *DbRoleAllData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GsGetRoleDataReq) Reset()                    { *m = GsGetRoleDataReq{} }
func (m *GsGetRoleDataReq) String() string            { return proto.CompactTextString(m) }
func (*GsGetRoleDataReq) ProtoMessage()               {}
func (*GsGetRoleDataReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *GsGetRoleDataReq) GetData() *DbRoleAllData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DbRoleDataAck struct {
	Data             *DbRoleAllData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *DbRoleDataAck) Reset()                    { *m = DbRoleDataAck{} }
func (m *DbRoleDataAck) String() string            { return proto.CompactTextString(m) }
func (*DbRoleDataAck) ProtoMessage()               {}
func (*DbRoleDataAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *DbRoleDataAck) GetData() *DbRoleAllData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GsRoleLeaveGame struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GsRoleLeaveGame) Reset()                    { *m = GsRoleLeaveGame{} }
func (m *GsRoleLeaveGame) String() string            { return proto.CompactTextString(m) }
func (*GsRoleLeaveGame) ProtoMessage()               {}
func (*GsRoleLeaveGame) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type SaveRoleReq struct {
	Data             *DbRoleAllData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *SaveRoleReq) Reset()                    { *m = SaveRoleReq{} }
func (m *SaveRoleReq) String() string            { return proto.CompactTextString(m) }
func (*SaveRoleReq) ProtoMessage()               {}
func (*SaveRoleReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *SaveRoleReq) GetData() *DbRoleAllData {
	if m != nil {
		return m.Data
	}
	return nil
}

type DbEnterGameCheckRoleReq struct {
	PlayerId         *uint64 `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	GateId           *uint64 `protobuf:"varint,2,req,name=gate_id" json:"gate_id,omitempty"`
	ClientId         *uint32 `protobuf:"varint,3,req,name=client_id" json:"client_id,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbEnterGameCheckRoleReq) Reset()                    { *m = DbEnterGameCheckRoleReq{} }
func (m *DbEnterGameCheckRoleReq) String() string            { return proto.CompactTextString(m) }
func (*DbEnterGameCheckRoleReq) ProtoMessage()               {}
func (*DbEnterGameCheckRoleReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *DbEnterGameCheckRoleReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *DbEnterGameCheckRoleReq) GetGateId() uint64 {
	if m != nil && m.GateId != nil {
		return *m.GateId
	}
	return 0
}

func (m *DbEnterGameCheckRoleReq) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *DbEnterGameCheckRoleReq) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GsEnterGameCheckRoleAck struct {
	PlayerId         *uint64 `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	GateId           *uint64 `protobuf:"varint,2,req,name=gate_id" json:"gate_id,omitempty"`
	ClientId         *uint32 `protobuf:"varint,3,req,name=client_id" json:"client_id,omitempty"`
	Name             *string `protobuf:"bytes,4,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GsEnterGameCheckRoleAck) Reset()                    { *m = GsEnterGameCheckRoleAck{} }
func (m *GsEnterGameCheckRoleAck) String() string            { return proto.CompactTextString(m) }
func (*GsEnterGameCheckRoleAck) ProtoMessage()               {}
func (*GsEnterGameCheckRoleAck) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *GsEnterGameCheckRoleAck) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GsEnterGameCheckRoleAck) GetGateId() uint64 {
	if m != nil && m.GateId != nil {
		return *m.GateId
	}
	return 0
}

func (m *GsEnterGameCheckRoleAck) GetClientId() uint32 {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return 0
}

func (m *GsEnterGameCheckRoleAck) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DbSkillData)(nil), "SProtoSpace.db_skill_data")
	proto.RegisterType((*DbHeroSoulData)(nil), "SProtoSpace.db_hero_soul_data")
	proto.RegisterType((*DbHeroData)(nil), "SProtoSpace.db_hero_data")
	proto.RegisterType((*DbItemPacket)(nil), "SProtoSpace.db_item_packet")
	proto.RegisterType((*DbJobData)(nil), "SProtoSpace.db_job_data")
	proto.RegisterType((*DbDropSpid)(nil), "SProtoSpace.db_drop_spid")
	proto.RegisterType((*DbEffect)(nil), "SProtoSpace.db_effect")
	proto.RegisterType((*DbSoulData)(nil), "SProtoSpace.db_soul_data")
	proto.RegisterType((*DbRoleAllData)(nil), "SProtoSpace.db_role_all_data")
	proto.RegisterType((*DbRoleAccountData)(nil), "SProtoSpace.db_role_account_data")
	proto.RegisterType((*GsGetRoleDataReq)(nil), "SProtoSpace.gs_get_role_data_req")
	proto.RegisterType((*DbRoleDataAck)(nil), "SProtoSpace.db_role_data_ack")
	proto.RegisterType((*GsRoleLeaveGame)(nil), "SProtoSpace.gs_role_leave_game")
	proto.RegisterType((*SaveRoleReq)(nil), "SProtoSpace.save_role_req")
	proto.RegisterType((*DbEnterGameCheckRoleReq)(nil), "SProtoSpace.db_enter_game_check_role_req")
	proto.RegisterType((*GsEnterGameCheckRoleAck)(nil), "SProtoSpace.gs_enter_game_check_role_ack")
	proto.RegisterEnum("SProtoSpace.ESaveRoleType", ESaveRoleType_name, ESaveRoleType_value)
	proto.RegisterEnum("SProtoSpace.EGS_DB_ProtoId", EGS_DB_ProtoId_name, EGS_DB_ProtoId_value)
}

func init() { proto.RegisterFile("gs_db.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1042 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x61, 0x6f, 0xe3, 0x44,
	0x13, 0x7e, 0xed, 0xd8, 0x69, 0x32, 0x8e, 0x5b, 0x77, 0xdb, 0x5e, 0xf7, 0xae, 0x7d, 0xb9, 0xc8,
	0x08, 0x11, 0x7a, 0xa8, 0x70, 0xfd, 0x70, 0x48, 0x27, 0x24, 0x10, 0x20, 0x21, 0xbe, 0x9d, 0xd4,
	0x1f, 0xb0, 0xda, 0xd8, 0xd3, 0x9c, 0x89, 0x63, 0x1b, 0xef, 0x3a, 0xd7, 0xfc, 0x1c, 0x7e, 0x0a,
	0xbf, 0x88, 0xcf, 0x7c, 0x43, 0x3b, 0x9b, 0xc4, 0x71, 0x08, 0x95, 0x4e, 0xe2, 0x53, 0xbb, 0xb3,
	0xcf, 0xce, 0x3c, 0xf3, 0xcc, 0x33, 0x0e, 0x04, 0x33, 0x25, 0xd2, 0xe9, 0x6d, 0x55, 0x97, 0xba,
	0x64, 0xc1, 0xfd, 0x3b, 0xf3, 0xf7, 0xbe, 0x92, 0x09, 0xbe, 0x80, 0xa9, 0x54, 0x68, 0x2f, 0xe2,
	0xef, 0x21, 0x4c, 0xa7, 0x42, 0xcd, 0xb3, 0x3c, 0x17, 0xa9, 0xd4, 0x92, 0x31, 0x00, 0x8d, 0x8b,
	0x2a, 0x97, 0x1a, 0xb3, 0x94, 0x3b, 0x63, 0x77, 0x12, 0xb2, 0x10, 0xfc, 0x1c, 0x97, 0x98, 0x73,
	0x77, 0xec, 0x4e, 0x7c, 0x36, 0x02, 0x4f, 0xe5, 0xa5, 0xe6, 0x3d, 0x73, 0x8a, 0xbf, 0x82, 0xd3,
	0x74, 0x2a, 0xde, 0x63, 0x5d, 0x0a, 0x55, 0x36, 0xeb, 0x2c, 0x23, 0xf0, 0x9a, 0x66, 0xfd, 0xde,
	0xdb, 0x3e, 0xa0, 0xe7, 0xf1, 0xef, 0x2e, 0x8c, 0x36, 0x2f, 0x0e, 0x80, 0xbb, 0x04, 0xdc, 0x2e,
	0x81, 0xde, 0x96, 0x80, 0x96, 0x35, 0xf7, 0xe8, 0x74, 0x03, 0x7d, 0xe2, 0xaf, 0xb8, 0x3f, 0xee,
	0x4d, 0x82, 0xbb, 0x17, 0xb7, 0x3b, 0xcd, 0xde, 0x76, 0xbb, 0x7b, 0x0d, 0x43, 0x22, 0x99, 0x67,
	0x4a, 0xf3, 0x3e, 0xc1, 0x3f, 0xd9, 0x87, 0xef, 0xb5, 0x72, 0x0c, 0x7d, 0xf9, 0x41, 0xce, 0xb1,
	0xe0, 0x47, 0x63, 0x77, 0x32, 0x60, 0x01, 0xf4, 0xf0, 0xb1, 0xe2, 0x03, 0xaa, 0xfd, 0x1a, 0x02,
	0x7b, 0x29, 0xa4, 0xd6, 0x35, 0x1f, 0x52, 0xc6, 0xeb, 0x4e, 0x46, 0x4a, 0x67, 0x6e, 0xc5, 0x52,
	0xe6, 0x0d, 0x9a, 0x7c, 0x79, 0x99, 0xcc, 0x31, 0xe5, 0x40, 0xf9, 0xce, 0x20, 0x48, 0x6a, 0x94,
	0x1a, 0x85, 0xce, 0x16, 0xc8, 0x83, 0xb1, 0x33, 0x09, 0xe3, 0x6f, 0xe0, 0x38, 0x9d, 0x8a, 0x4c,
	0xe3, 0x42, 0x54, 0x32, 0x99, 0xa3, 0x66, 0x9f, 0x81, 0x6f, 0x8e, 0x8a, 0x3b, 0x54, 0xe3, 0x59,
	0xa7, 0x06, 0x01, 0x0d, 0xdb, 0x58, 0x43, 0x90, 0x4e, 0xc5, 0xaf, 0xe5, 0x74, 0x4b, 0xde, 0xfc,
	0x4f, 0xe2, 0x3a, 0x56, 0x39, 0xbd, 0xaa, 0x90, 0xbb, 0x74, 0x62, 0x00, 0x99, 0x12, 0x35, 0x26,
	0x98, 0x2d, 0x91, 0xf7, 0xc6, 0xce, 0x64, 0xc0, 0x4e, 0xe0, 0x28, 0x53, 0x22, 0x2f, 0xcb, 0x39,
	0xf7, 0x28, 0x10, 0xc1, 0x20, 0x69, 0x6a, 0xa1, 0x34, 0x56, 0xdc, 0x37, 0xe4, 0x4c, 0x64, 0x21,
	0x1f, 0x6d, 0xa4, 0xbf, 0xa6, 0x6b, 0x26, 0x9a, 0xd6, 0x65, 0x25, 0x54, 0x95, 0xa5, 0x0c, 0xc0,
	0xdd, 0x2d, 0x49, 0x48, 0x5b, 0x32, 0x04, 0x9f, 0x64, 0xa0, 0x6a, 0x7e, 0xfc, 0x0e, 0x86, 0xe9,
	0x54, 0xe0, 0xc3, 0x03, 0x26, 0x7a, 0xff, 0xd5, 0x0e, 0xd1, 0x10, 0x7c, 0x73, 0xba, 0xb3, 0xaf,
	0xcc, 0x08, 0x8a, 0x66, 0x41, 0xfc, 0xec, 0x5d, 0xa9, 0x65, 0x4e, 0xe4, 0xfc, 0xf8, 0x2f, 0x87,
	0xb8, 0xb4, 0xf3, 0x0b, 0xa0, 0xd7, 0xac, 0xd3, 0x7a, 0x46, 0xec, 0x8d, 0xb9, 0x04, 0xb9, 0xcb,
	0x64, 0x00, 0x70, 0xf3, 0x65, 0x9b, 0xda, 0x4c, 0xd7, 0x6b, 0xa9, 0xcb, 0xda, 0x66, 0x66, 0xa7,
	0x30, 0xac, 0x4a, 0x25, 0xb2, 0x22, 0xc5, 0x47, 0xea, 0x9b, 0x42, 0xaa, 0xc9, 0xb4, 0x20, 0xaa,
	0x47, 0x14, 0x8a, 0x60, 0x40, 0x13, 0x37, 0x35, 0x07, 0x54, 0x73, 0xa3, 0x68, 0x32, 0xe7, 0x43,
	0x52, 0xf4, 0x15, 0x04, 0x0b, 0x99, 0x15, 0xeb, 0xb6, 0x39, 0x1c, 0x18, 0x68, 0x2b, 0xca, 0x0d,
	0x80, 0x4c, 0xd3, 0x0d, 0x36, 0x78, 0x0a, 0x1b, 0xff, 0xe9, 0x41, 0x94, 0x4e, 0x45, 0x5d, 0xe6,
	0x28, 0xe4, 0xc6, 0xf2, 0x27, 0x70, 0x34, 0x5b, 0xb7, 0xeb, 0x6c, 0xf8, 0x10, 0x62, 0xdd, 0xbf,
	0x67, 0xba, 0xa0, 0x40, 0x21, 0x17, 0x76, 0x2e, 0x43, 0xe3, 0x0c, 0x99, 0x24, 0x65, 0x53, 0x68,
	0x03, 0xf3, 0x28, 0x76, 0x01, 0x61, 0x2e, 0x95, 0xce, 0x51, 0x2e, 0x91, 0xac, 0x6a, 0xdd, 0x40,
	0xf9, 0x17, 0x94, 0xae, 0x4f, 0xe9, 0x2e, 0x20, 0x2c, 0x4a, 0x9d, 0x3d, 0xac, 0x44, 0x92, 0x67,
	0x58, 0xe8, 0xb5, 0x30, 0x56, 0xe5, 0xc1, 0xae, 0xca, 0xc3, 0xcd, 0x41, 0xe1, 0x23, 0x07, 0x3a,
	0x7c, 0x09, 0x43, 0x92, 0x8f, 0x16, 0xd4, 0x76, 0xfb, 0xfc, 0xe0, 0x82, 0x52, 0x6f, 0x5f, 0x43,
	0xb0, 0xb3, 0x23, 0x7c, 0x34, 0x76, 0x26, 0xc1, 0xdd, 0xd5, 0x3e, 0x7e, 0x77, 0x8d, 0xde, 0x00,
	0xb3, 0xc7, 0xba, 0xac, 0xb0, 0xd6, 0x2b, 0x91, 0x15, 0x0f, 0x25, 0x3f, 0x39, 0xf0, 0xe1, 0xe8,
	0xc0, 0xd8, 0xe7, 0xe0, 0x9b, 0x45, 0x52, 0x3c, 0x22, 0x28, 0xdf, 0xaf, 0xb1, 0xdd, 0xb8, 0x4b,
	0x38, 0xa9, 0xa4, 0xd2, 0x42, 0x25, 0x58, 0x18, 0x51, 0x84, 0xe2, 0xa7, 0xe3, 0xde, 0xc4, 0x67,
	0xb7, 0x10, 0x6c, 0x17, 0x44, 0x28, 0xce, 0x0e, 0xf7, 0xd6, 0xee, 0xd0, 0x17, 0xd0, 0x27, 0x13,
	0x2b, 0x7e, 0x76, 0x18, 0xda, 0x5a, 0x3c, 0x82, 0x41, 0x95, 0x97, 0x66, 0x54, 0x8a, 0x9f, 0x53,
	0xb1, 0x37, 0x10, 0x9a, 0x8f, 0xbc, 0x98, 0x36, 0x2b, 0x82, 0xf0, 0x0b, 0x92, 0xe6, 0x65, 0x27,
	0x07, 0x0d, 0xbd, 0x03, 0x63, 0x57, 0x10, 0x66, 0x4a, 0x14, 0xf8, 0x41, 0x54, 0xb9, 0x5c, 0x61,
	0xcd, 0x9f, 0x19, 0xc7, 0xbe, 0xf5, 0x74, 0xdd, 0x20, 0xb9, 0x5d, 0x2e, 0xd1, 0xba, 0xfd, 0x92,
	0xb6, 0xed, 0x2d, 0x9c, 0x6f, 0x0d, 0xb7, 0xf6, 0xcb, 0xc6, 0x74, 0x1b, 0x8f, 0xd9, 0xaf, 0x7a,
	0xc7, 0x63, 0xe6, 0xa3, 0x3e, 0x8c, 0x7f, 0x84, 0xf3, 0x99, 0x12, 0x33, 0xd4, 0xf6, 0xbd, 0x79,
	0x27, 0x6a, 0xfc, 0x8d, 0xbd, 0x02, 0x8f, 0x28, 0x3b, 0x44, 0xf9, 0xff, 0xfb, 0x6d, 0x77, 0xdc,
	0x1d, 0x7f, 0xd7, 0x3a, 0x9e, 0x12, 0xc8, 0x64, 0xfe, 0x71, 0x09, 0xce, 0x81, 0xcd, 0x94, 0x8d,
	0x91, 0xb3, 0x85, 0x31, 0x73, 0xfc, 0x2d, 0x84, 0xd4, 0x2a, 0xc5, 0x3f, 0x9a, 0x54, 0x02, 0xd7,
	0x66, 0x29, 0x0b, 0x8d, 0x35, 0xa5, 0x13, 0xc9, 0x7b, 0x4c, 0xe6, 0x6d, 0x32, 0xf3, 0x25, 0x21,
	0x79, 0x5b, 0x7d, 0x76, 0xb6, 0xd4, 0xdd, 0x08, 0x66, 0xd7, 0xc7, 0x84, 0x7a, 0xf4, 0x2b, 0x38,
	0x02, 0x8f, 0xe4, 0xf3, 0x48, 0xbe, 0x04, 0xae, 0x67, 0xea, 0x5f, 0x8a, 0x18, 0x15, 0xfe, 0x8b,
	0x22, 0x37, 0x0a, 0x22, 0x14, 0xad, 0x12, 0x66, 0xf2, 0x0c, 0xa0, 0x8f, 0xa2, 0x28, 0x0b, 0x8c,
	0xfe, 0xc7, 0x22, 0x18, 0x91, 0x85, 0xb2, 0x84, 0x16, 0x29, 0x72, 0xd8, 0x09, 0x04, 0x68, 0x37,
	0x94, 0x02, 0xae, 0x0d, 0xd0, 0x32, 0x51, 0xa0, 0xc7, 0x8e, 0x01, 0x90, 0xf6, 0x85, 0xce, 0x9e,
	0x05, 0x90, 0x99, 0x29, 0xe0, 0xdf, 0xfc, 0xe1, 0xc0, 0x31, 0xfe, 0x7c, 0x2f, 0x7e, 0xfa, 0x41,
	0x90, 0xca, 0xbf, 0xa4, 0xec, 0x0a, 0x2e, 0x0f, 0x79, 0x45, 0x64, 0x69, 0xe4, 0xb0, 0x4b, 0x38,
	0xdb, 0xf7, 0x80, 0xb9, 0x70, 0xd9, 0x73, 0xb8, 0xf8, 0xe7, 0x6c, 0xcd, 0x55, 0x8f, 0x9d, 0x43,
	0xd4, 0x19, 0xb0, 0x89, 0x7a, 0xec, 0x53, 0x78, 0xf9, 0xd4, 0xe0, 0x0c, 0xc8, 0x37, 0xa0, 0xa7,
	0x84, 0x37, 0xa0, 0xfe, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xd9, 0x01, 0x1b, 0x7e, 0x09,
	0x00, 0x00,
}
