// Code generated by protoc-gen-go.
// source: gs_gt.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EProtoId int32

const (
	EProtoId_player_enter_game_server_id  EProtoId = 2
	EProtoId_gs_broadcast_req_id          EProtoId = 3
	EProtoId_gs_change_name_req_id        EProtoId = 4
	EProtoId_gt_change_name_ret_id        EProtoId = 5
	EProtoId_gs_jump_to_cross_game_req_id EProtoId = 6
	EProtoId_gs_kick_role_ntf_id          EProtoId = 7
	EProtoId_gs_player_num_ntf_id         EProtoId = 8
)

var EProtoId_name = map[int32]string{
	2: "player_enter_game_server_id",
	3: "gs_broadcast_req_id",
	4: "gs_change_name_req_id",
	5: "gt_change_name_ret_id",
	6: "gs_jump_to_cross_game_req_id",
	7: "gs_kick_role_ntf_id",
	8: "gs_player_num_ntf_id",
}
var EProtoId_value = map[string]int32{
	"player_enter_game_server_id":  2,
	"gs_broadcast_req_id":          3,
	"gs_change_name_req_id":        4,
	"gt_change_name_ret_id":        5,
	"gs_jump_to_cross_game_req_id": 6,
	"gs_kick_role_ntf_id":          7,
	"gs_player_num_ntf_id":         8,
}

func (x EProtoId) Enum() *EProtoId {
	p := new(EProtoId)
	*p = x
	return p
}
func (x EProtoId) String() string {
	return proto.EnumName(EProtoId_name, int32(x))
}
func (x *EProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EProtoId_value, data, "EProtoId")
	if err != nil {
		return err
	}
	*x = EProtoId(value)
	return nil
}
func (EProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type PlayerEnterGameServer struct {
	PlayerId   *uint64 `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	PlayerName *string `protobuf:"bytes,2,req,name=player_name" json:"player_name,omitempty"`
	Account    *string `protobuf:"bytes,3,req,name=account" json:"account,omitempty"`
	// whether should notify client:0,no; else yes
	NotifyClient     *int32  `protobuf:"varint,4,req,name=notify_client" json:"notify_client,omitempty"`
	DbserverId       *uint64 `protobuf:"varint,5,req,name=dbserver_id" json:"dbserver_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerEnterGameServer) Reset()                    { *m = PlayerEnterGameServer{} }
func (m *PlayerEnterGameServer) String() string            { return proto.CompactTextString(m) }
func (*PlayerEnterGameServer) ProtoMessage()               {}
func (*PlayerEnterGameServer) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *PlayerEnterGameServer) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *PlayerEnterGameServer) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerEnterGameServer) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *PlayerEnterGameServer) GetNotifyClient() int32 {
	if m != nil && m.NotifyClient != nil {
		return *m.NotifyClient
	}
	return 0
}

func (m *PlayerEnterGameServer) GetDbserverId() uint64 {
	if m != nil && m.DbserverId != nil {
		return *m.DbserverId
	}
	return 0
}

// game broadcast req
type GsBroadcastReq struct {
	Proto            []byte `protobuf:"bytes,2,req,name=proto" json:"proto,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GsBroadcastReq) Reset()                    { *m = GsBroadcastReq{} }
func (m *GsBroadcastReq) String() string            { return proto.CompactTextString(m) }
func (*GsBroadcastReq) ProtoMessage()               {}
func (*GsBroadcastReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *GsBroadcastReq) GetProto() []byte {
	if m != nil {
		return m.Proto
	}
	return nil
}

// change name req
type GsChangeNameReq struct {
	NewName          *string `protobuf:"bytes,1,req,name=new_name" json:"new_name,omitempty"`
	OldName          *string `protobuf:"bytes,2,req,name=old_name" json:"old_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GsChangeNameReq) Reset()                    { *m = GsChangeNameReq{} }
func (m *GsChangeNameReq) String() string            { return proto.CompactTextString(m) }
func (*GsChangeNameReq) ProtoMessage()               {}
func (*GsChangeNameReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *GsChangeNameReq) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

func (m *GsChangeNameReq) GetOldName() string {
	if m != nil && m.OldName != nil {
		return *m.OldName
	}
	return ""
}

type GtChangeNameRet struct {
	NewName          *string `protobuf:"bytes,1,req,name=new_name" json:"new_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtChangeNameRet) Reset()                    { *m = GtChangeNameRet{} }
func (m *GtChangeNameRet) String() string            { return proto.CompactTextString(m) }
func (*GtChangeNameRet) ProtoMessage()               {}
func (*GtChangeNameRet) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *GtChangeNameRet) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

type GsJumpToCrossGameReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GsJumpToCrossGameReq) Reset()                    { *m = GsJumpToCrossGameReq{} }
func (m *GsJumpToCrossGameReq) String() string            { return proto.CompactTextString(m) }
func (*GsJumpToCrossGameReq) ProtoMessage()               {}
func (*GsJumpToCrossGameReq) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

type GsKickRoleNtf struct {
	PlayerId         *uint64 `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	Reason           *int32  `protobuf:"varint,2,req,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GsKickRoleNtf) Reset()                    { *m = GsKickRoleNtf{} }
func (m *GsKickRoleNtf) String() string            { return proto.CompactTextString(m) }
func (*GsKickRoleNtf) ProtoMessage()               {}
func (*GsKickRoleNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *GsKickRoleNtf) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *GsKickRoleNtf) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type GsPlayerNumNtf struct {
	PlayerNum        *uint32 `protobuf:"varint,1,req,name=player_num" json:"player_num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GsPlayerNumNtf) Reset()                    { *m = GsPlayerNumNtf{} }
func (m *GsPlayerNumNtf) String() string            { return proto.CompactTextString(m) }
func (*GsPlayerNumNtf) ProtoMessage()               {}
func (*GsPlayerNumNtf) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *GsPlayerNumNtf) GetPlayerNum() uint32 {
	if m != nil && m.PlayerNum != nil {
		return *m.PlayerNum
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerEnterGameServer)(nil), "SProtoSpace.player_enter_game_server")
	proto.RegisterType((*GsBroadcastReq)(nil), "SProtoSpace.gs_broadcast_req")
	proto.RegisterType((*GsChangeNameReq)(nil), "SProtoSpace.gs_change_name_req")
	proto.RegisterType((*GtChangeNameRet)(nil), "SProtoSpace.gt_change_name_ret")
	proto.RegisterType((*GsJumpToCrossGameReq)(nil), "SProtoSpace.gs_jump_to_cross_game_req")
	proto.RegisterType((*GsKickRoleNtf)(nil), "SProtoSpace.gs_kick_role_ntf")
	proto.RegisterType((*GsPlayerNumNtf)(nil), "SProtoSpace.gs_player_num_ntf")
	proto.RegisterEnum("SProtoSpace.EProtoId", EProtoId_name, EProtoId_value)
}

func init() { proto.RegisterFile("gs_gt.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x45, 0x20, 0x10, 0x86, 0x65, 0x37, 0x98, 0x45, 0x1b, 0x96, 0x95, 0x36, 0x9b, 0xc3,
	0x16, 0xf5, 0xd0, 0x5b, 0xa5, 0xbe, 0x42, 0x6f, 0x95, 0x78, 0x00, 0xcb, 0x38, 0x83, 0x9b, 0x92,
	0xd8, 0xc1, 0x36, 0xad, 0x38, 0xf5, 0x11, 0xfb, 0x4a, 0x95, 0x1d, 0xaa, 0xb6, 0xa4, 0x9c, 0x2c,
	0xcd, 0xe7, 0x7f, 0xe6, 0x9f, 0x7f, 0x60, 0x24, 0x0c, 0x15, 0xf6, 0xaa, 0xd6, 0xca, 0x2a, 0x32,
	0x5a, 0xdd, 0xb9, 0x77, 0x55, 0x33, 0x8e, 0xbf, 0x61, 0xcd, 0x0c, 0x36, 0x20, 0x7b, 0x86, 0xa4,
	0x2e, 0xd9, 0x01, 0x35, 0x45, 0x69, 0x51, 0x53, 0xc1, 0x2a, 0xa4, 0x06, 0xf5, 0x23, 0x6a, 0x32,
	0x81, 0xe1, 0x91, 0x15, 0x79, 0xd2, 0x49, 0x83, 0x65, 0x8f, 0x4c, 0x61, 0x74, 0x2c, 0x49, 0x56,
	0x61, 0x12, 0xa4, 0xc1, 0x72, 0x48, 0x7e, 0xc0, 0x80, 0x71, 0xae, 0xf6, 0xd2, 0x26, 0x5d, 0x5f,
	0x98, 0xc1, 0x58, 0x2a, 0x5b, 0x6c, 0x0e, 0x94, 0x97, 0x05, 0x4a, 0x9b, 0xf4, 0xd2, 0x60, 0x19,
	0x3a, 0x71, 0xbe, 0x6e, 0x7a, 0xbb, 0x8e, 0xa1, 0xeb, 0x98, 0xfd, 0x83, 0x58, 0x18, 0xba, 0xd6,
	0x8a, 0xe5, 0x9c, 0x19, 0x4b, 0x35, 0xee, 0xc8, 0x18, 0x42, 0xef, 0xce, 0xf7, 0xff, 0x96, 0xdd,
	0x00, 0x11, 0x86, 0xf2, 0x7b, 0x26, 0x05, 0xfa, 0xb9, 0xfe, 0x53, 0x0c, 0x91, 0xc4, 0xa7, 0xc6,
	0x47, 0xc7, 0x8f, 0x8d, 0x21, 0x52, 0x65, 0xfe, 0xc1, 0x59, 0xf6, 0x1f, 0x88, 0xb0, 0x27, 0x4a,
	0xdb, 0x56, 0x66, 0x0b, 0x98, 0x0b, 0x43, 0x1f, 0xf6, 0x55, 0x4d, 0xad, 0xa2, 0x5c, 0x2b, 0x63,
	0x9a, 0x24, 0x34, 0xee, 0xb2, 0x6b, 0xef, 0x70, 0x5b, 0xf0, 0x2d, 0xd5, 0xaa, 0x44, 0x2a, 0xed,
	0xe6, 0xab, 0x68, 0xbe, 0x43, 0x5f, 0x23, 0x33, 0x4a, 0xfa, 0xd9, 0x61, 0x76, 0x01, 0x13, 0x61,
	0xe8, 0x5b, 0x5a, 0xfb, 0xca, 0xeb, 0x08, 0xc0, 0x7b, 0xc5, 0x0b, 0xc7, 0x97, 0x2f, 0x1d, 0x88,
	0xd0, 0x9f, 0xe7, 0x36, 0x27, 0x7f, 0x61, 0x71, 0xee, 0x1e, 0xb4, 0xc8, 0xe3, 0x80, 0xfc, 0x82,
	0xe9, 0x69, 0x5e, 0x0e, 0x74, 0xc9, 0x1c, 0x66, 0xed, 0x94, 0x1c, 0xea, 0x79, 0xd4, 0x8a, 0xc1,
	0xa1, 0x90, 0xa4, 0xf0, 0xe7, 0xec, 0xe6, 0xee, 0x47, 0xff, 0x38, 0xf0, 0xd3, 0xfa, 0x0e, 0x0c,
	0x48, 0x02, 0x3f, 0x5b, 0x0b, 0x3a, 0x12, 0xbd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x62, 0xfb, 0x9c,
	0x43, 0x7b, 0x02, 0x00, 0x00,
}
