// Code generated by protoc-gen-go.
// source: gt_center.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EProtId int32

const (
	EProtId_gate_listen_report_id            EProtId = 1
	EProtId_gate_player_num_report_id        EProtId = 2
	EProtId_role_login_verify_req_id         EProtId = 3
	EProtId_role_login_verify_ack_id         EProtId = 4
	EProtId_gt_game_server_player_num_ntf_id EProtId = 5
	EProtId_ct_need_queued_ntf_id            EProtId = 13
	EProtId_ct_end_queued_ntf_id             EProtId = 14
	EProtId_gt_queued_state_req_id           EProtId = 15
	EProtId_ct_queued_state_ack_id           EProtId = 16
	EProtId_gt_cancel_queue_req_id           EProtId = 17
	EProtId_ct_cancel_queue_ack_id           EProtId = 18
)

var EProtId_name = map[int32]string{
	1:  "gate_listen_report_id",
	2:  "gate_player_num_report_id",
	3:  "role_login_verify_req_id",
	4:  "role_login_verify_ack_id",
	5:  "gt_game_server_player_num_ntf_id",
	13: "ct_need_queued_ntf_id",
	14: "ct_end_queued_ntf_id",
	15: "gt_queued_state_req_id",
	16: "ct_queued_state_ack_id",
	17: "gt_cancel_queue_req_id",
	18: "ct_cancel_queue_ack_id",
}
var EProtId_value = map[string]int32{
	"gate_listen_report_id":            1,
	"gate_player_num_report_id":        2,
	"role_login_verify_req_id":         3,
	"role_login_verify_ack_id":         4,
	"gt_game_server_player_num_ntf_id": 5,
	"ct_need_queued_ntf_id":            13,
	"ct_end_queued_ntf_id":             14,
	"gt_queued_state_req_id":           15,
	"ct_queued_state_ack_id":           16,
	"gt_cancel_queue_req_id":           17,
	"ct_cancel_queue_ack_id":           18,
}

func (x EProtId) Enum() *EProtId {
	p := new(EProtId)
	*p = x
	return p
}
func (x EProtId) String() string {
	return proto.EnumName(EProtId_name, int32(x))
}
func (x *EProtId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EProtId_value, data, "EProtId")
	if err != nil {
		return err
	}
	*x = EProtId(value)
	return nil
}
func (EProtId) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type GateListenReport struct {
	Ip               *string `protobuf:"bytes,1,req,name=Ip" json:"Ip,omitempty"`
	Port             *int32  `protobuf:"varint,2,req,name=Port" json:"Port,omitempty"`
	GroupName        *string `protobuf:"bytes,3,req,name=GroupName" json:"GroupName,omitempty"`
	New              *bool   `protobuf:"varint,4,req,name=new" json:"new,omitempty"`
	State            *int32  `protobuf:"varint,5,req,name=state" json:"state,omitempty"`
	Groupindex       *uint32 `protobuf:"varint,6,req,name=groupindex" json:"groupindex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GateListenReport) Reset()                    { *m = GateListenReport{} }
func (m *GateListenReport) String() string            { return proto.CompactTextString(m) }
func (*GateListenReport) ProtoMessage()               {}
func (*GateListenReport) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *GateListenReport) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *GateListenReport) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *GateListenReport) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *GateListenReport) GetNew() bool {
	if m != nil && m.New != nil {
		return *m.New
	}
	return false
}

func (m *GateListenReport) GetState() int32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *GateListenReport) GetGroupindex() uint32 {
	if m != nil && m.Groupindex != nil {
		return *m.Groupindex
	}
	return 0
}

type GatePlayerNumReport struct {
	Num              *int32 `protobuf:"varint,1,req,name=num" json:"num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GatePlayerNumReport) Reset()                    { *m = GatePlayerNumReport{} }
func (m *GatePlayerNumReport) String() string            { return proto.CompactTextString(m) }
func (*GatePlayerNumReport) ProtoMessage()               {}
func (*GatePlayerNumReport) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *GatePlayerNumReport) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type RoleLoginVerifyReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Token            *int32  `protobuf:"varint,3,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoleLoginVerifyReq) Reset()                    { *m = RoleLoginVerifyReq{} }
func (m *RoleLoginVerifyReq) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginVerifyReq) ProtoMessage()               {}
func (*RoleLoginVerifyReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *RoleLoginVerifyReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RoleLoginVerifyReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *RoleLoginVerifyReq) GetToken() int32 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

type RoleLoginVerifyAck struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	VerifyRet        *int32  `protobuf:"varint,3,req,name=verify_ret" json:"verify_ret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoleLoginVerifyAck) Reset()                    { *m = RoleLoginVerifyAck{} }
func (m *RoleLoginVerifyAck) String() string            { return proto.CompactTextString(m) }
func (*RoleLoginVerifyAck) ProtoMessage()               {}
func (*RoleLoginVerifyAck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *RoleLoginVerifyAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *RoleLoginVerifyAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *RoleLoginVerifyAck) GetVerifyRet() int32 {
	if m != nil && m.VerifyRet != nil {
		return *m.VerifyRet
	}
	return 0
}

type GtOnlineClientNtf struct {
	Accountid        []uint32 `protobuf:"varint,1,rep,name=accountid" json:"accountid,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GtOnlineClientNtf) Reset()                    { *m = GtOnlineClientNtf{} }
func (m *GtOnlineClientNtf) String() string            { return proto.CompactTextString(m) }
func (*GtOnlineClientNtf) ProtoMessage()               {}
func (*GtOnlineClientNtf) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *GtOnlineClientNtf) GetAccountid() []uint32 {
	if m != nil {
		return m.Accountid
	}
	return nil
}

type GtGameServerPlayerNumNtf struct {
	GameServerId     *uint32 `protobuf:"varint,1,req,name=game_server_id" json:"game_server_id,omitempty"`
	PlayerNum        *uint32 `protobuf:"varint,2,req,name=player_num" json:"player_num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtGameServerPlayerNumNtf) Reset()                    { *m = GtGameServerPlayerNumNtf{} }
func (m *GtGameServerPlayerNumNtf) String() string            { return proto.CompactTextString(m) }
func (*GtGameServerPlayerNumNtf) ProtoMessage()               {}
func (*GtGameServerPlayerNumNtf) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *GtGameServerPlayerNumNtf) GetGameServerId() uint32 {
	if m != nil && m.GameServerId != nil {
		return *m.GameServerId
	}
	return 0
}

func (m *GtGameServerPlayerNumNtf) GetPlayerNum() uint32 {
	if m != nil && m.PlayerNum != nil {
		return *m.PlayerNum
	}
	return 0
}

type CtNeedQueuedNtf struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Pos              *uint32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CtNeedQueuedNtf) Reset()                    { *m = CtNeedQueuedNtf{} }
func (m *CtNeedQueuedNtf) String() string            { return proto.CompactTextString(m) }
func (*CtNeedQueuedNtf) ProtoMessage()               {}
func (*CtNeedQueuedNtf) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *CtNeedQueuedNtf) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *CtNeedQueuedNtf) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type CtEndQueuedNtf struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CtEndQueuedNtf) Reset()                    { *m = CtEndQueuedNtf{} }
func (m *CtEndQueuedNtf) String() string            { return proto.CompactTextString(m) }
func (*CtEndQueuedNtf) ProtoMessage()               {}
func (*CtEndQueuedNtf) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *CtEndQueuedNtf) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

type GtQueuedStateReq struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Accountid        *uint32 `protobuf:"varint,2,req,name=accountid" json:"accountid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtQueuedStateReq) Reset()                    { *m = GtQueuedStateReq{} }
func (m *GtQueuedStateReq) String() string            { return proto.CompactTextString(m) }
func (*GtQueuedStateReq) ProtoMessage()               {}
func (*GtQueuedStateReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *GtQueuedStateReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *GtQueuedStateReq) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

type CtQueuedStateAck struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Pos              *uint32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CtQueuedStateAck) Reset()                    { *m = CtQueuedStateAck{} }
func (m *CtQueuedStateAck) String() string            { return proto.CompactTextString(m) }
func (*CtQueuedStateAck) ProtoMessage()               {}
func (*CtQueuedStateAck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *CtQueuedStateAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *CtQueuedStateAck) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type GtCancelQueueReq struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Accountid        *uint32 `protobuf:"varint,2,req,name=accountid" json:"accountid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GtCancelQueueReq) Reset()                    { *m = GtCancelQueueReq{} }
func (m *GtCancelQueueReq) String() string            { return proto.CompactTextString(m) }
func (*GtCancelQueueReq) ProtoMessage()               {}
func (*GtCancelQueueReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *GtCancelQueueReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *GtCancelQueueReq) GetAccountid() uint32 {
	if m != nil && m.Accountid != nil {
		return *m.Accountid
	}
	return 0
}

type CtCancelQueueAck struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CtCancelQueueAck) Reset()                    { *m = CtCancelQueueAck{} }
func (m *CtCancelQueueAck) String() string            { return proto.CompactTextString(m) }
func (*CtCancelQueueAck) ProtoMessage()               {}
func (*CtCancelQueueAck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *CtCancelQueueAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func init() {
	proto.RegisterType((*GateListenReport)(nil), "SProtoSpace.gate_listen_report")
	proto.RegisterType((*GatePlayerNumReport)(nil), "SProtoSpace.gate_player_num_report")
	proto.RegisterType((*RoleLoginVerifyReq)(nil), "SProtoSpace.role_login_verify_req")
	proto.RegisterType((*RoleLoginVerifyAck)(nil), "SProtoSpace.role_login_verify_ack")
	proto.RegisterType((*GtOnlineClientNtf)(nil), "SProtoSpace.gt_online_client_ntf")
	proto.RegisterType((*GtGameServerPlayerNumNtf)(nil), "SProtoSpace.gt_game_server_player_num_ntf")
	proto.RegisterType((*CtNeedQueuedNtf)(nil), "SProtoSpace.ct_need_queued_ntf")
	proto.RegisterType((*CtEndQueuedNtf)(nil), "SProtoSpace.ct_end_queued_ntf")
	proto.RegisterType((*GtQueuedStateReq)(nil), "SProtoSpace.gt_queued_state_req")
	proto.RegisterType((*CtQueuedStateAck)(nil), "SProtoSpace.ct_queued_state_ack")
	proto.RegisterType((*GtCancelQueueReq)(nil), "SProtoSpace.gt_cancel_queue_req")
	proto.RegisterType((*CtCancelQueueAck)(nil), "SProtoSpace.ct_cancel_queue_ack")
	proto.RegisterEnum("SProtoSpace.EProtId", EProtId_name, EProtId_value)
}

func init() { proto.RegisterFile("gt_center.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x56, 0x9c, 0xb8, 0xc0, 0xa4, 0x21, 0xc9, 0x02, 0x91, 0x41, 0x45, 0xb2, 0xac, 0xa2, 0xba,
	0x3d, 0xf4, 0xd2, 0x9e, 0xfa, 0x02, 0x55, 0x54, 0x09, 0x21, 0xf1, 0x00, 0xab, 0xed, 0x7a, 0xb0,
	0xac, 0x38, 0xbb, 0xce, 0x7a, 0x4c, 0xcb, 0x2b, 0xf6, 0xa9, 0xaa, 0x59, 0x9b, 0x36, 0x24, 0x16,
	0x70, 0xda, 0xc3, 0xf7, 0xbb, 0x33, 0x03, 0xd3, 0x9c, 0xa4, 0x46, 0x43, 0xe8, 0x3e, 0x57, 0xce,
	0x92, 0x15, 0xe3, 0xdb, 0x1b, 0x7e, 0x6f, 0x2b, 0xa5, 0xf1, 0x02, 0x7e, 0xaa, 0x1a, 0x5b, 0x20,
	0xd9, 0x80, 0xc8, 0x15, 0xa1, 0x2c, 0x8b, 0x9a, 0xd0, 0x48, 0x87, 0x95, 0x75, 0x24, 0x00, 0x82,
	0x65, 0x15, 0x0d, 0xe2, 0x20, 0x3d, 0x12, 0x6f, 0x61, 0x74, 0x63, 0x1d, 0x45, 0x41, 0x1c, 0xa4,
	0xa1, 0x98, 0xc3, 0xd1, 0x77, 0x67, 0x9b, 0xea, 0x5a, 0xad, 0x31, 0x1a, 0x7a, 0xc2, 0x18, 0x86,
	0x06, 0x7f, 0x45, 0xa3, 0x38, 0x48, 0x0f, 0xc5, 0x04, 0xc2, 0x9a, 0x14, 0x61, 0x14, 0x7a, 0xba,
	0x00, 0xc8, 0x99, 0x5e, 0x98, 0x0c, 0x7f, 0x47, 0x6f, 0xe2, 0x20, 0x9d, 0x24, 0x57, 0xb0, 0xf0,
	0x91, 0x55, 0xa9, 0x1e, 0xd0, 0x49, 0xd3, 0xac, 0x1f, 0x63, 0xd9, 0xa9, 0x59, 0xfb, 0xdc, 0x30,
	0x59, 0xc2, 0x99, 0xb3, 0x25, 0xca, 0xd2, 0xe6, 0x85, 0x91, 0xf7, 0xe8, 0x8a, 0xbb, 0x07, 0xe9,
	0x70, 0x23, 0xa6, 0x70, 0xa0, 0xb4, 0xb6, 0x8d, 0xa1, 0xae, 0xe1, 0x0c, 0x0e, 0x75, 0x59, 0xa0,
	0xa1, 0x22, 0xf3, 0x2d, 0x27, 0xdc, 0x82, 0xec, 0x0a, 0x8d, 0x6f, 0x18, 0x26, 0xd7, 0x7d, 0x56,
	0x4a, 0xaf, 0x5e, 0x63, 0x25, 0x00, 0xfe, 0x65, 0x53, 0xe7, 0xf7, 0x11, 0x4e, 0x73, 0x92, 0xd6,
	0x94, 0x85, 0x41, 0xd9, 0xf2, 0xa5, 0xa1, 0x3b, 0x1e, 0x4e, 0x67, 0x57, 0x64, 0xd1, 0x20, 0x1e,
	0xa6, 0x93, 0xe4, 0x07, 0x5c, 0xe6, 0x24, 0x73, 0xb5, 0x46, 0x59, 0xa3, 0xbb, 0x47, 0xb7, 0xfd,
	0x6d, 0xd6, 0x2c, 0xe0, 0x78, 0x1b, 0xf5, 0xc2, 0x2e, 0xf7, 0x3f, 0xb3, 0xed, 0x92, 0x7c, 0x01,
	0xa1, 0x49, 0x1a, 0xc4, 0x4c, 0x6e, 0x1a, 0x6c, 0x30, 0xf3, 0x0e, 0xdb, 0x9d, 0x5b, 0xed, 0x18,
	0x86, 0x95, 0xad, 0x3b, 0xd1, 0x15, 0xcc, 0x35, 0x49, 0x34, 0xcf, 0x6b, 0x92, 0x6f, 0x70, 0x92,
	0xd3, 0x23, 0xc5, 0xaf, 0xd0, 0x0f, 0x7b, 0xdf, 0xfc, 0xc9, 0x27, 0xdb, 0x88, 0xaf, 0x70, 0xa2,
	0x77, 0xb4, 0x3c, 0xdd, 0x17, 0x8a, 0xb5, 0x89, 0x5a, 0x19, 0x8d, 0x65, 0x2b, 0x7e, 0x7d, 0xe2,
	0x07, 0x9f, 0xf8, 0x44, 0xdb, 0x9b, 0xf8, 0xe9, 0x4f, 0x00, 0x07, 0xc8, 0xb7, 0xbf, 0xcc, 0xc4,
	0x39, 0x9c, 0xed, 0xdf, 0xba, 0x2c, 0xb2, 0xd9, 0x40, 0x5c, 0xc2, 0x79, 0xff, 0x4d, 0x32, 0x1c,
	0x88, 0x77, 0x10, 0xf5, 0xde, 0x22, 0xa3, 0xc3, 0x7e, 0x54, 0xe9, 0x15, 0xa3, 0x23, 0xf1, 0x1e,
	0xe2, 0x67, 0x2f, 0x80, 0x59, 0x21, 0x77, 0xdb, 0x5f, 0x2d, 0x43, 0x13, 0x11, 0xc1, 0xe9, 0xde,
	0x02, 0x19, 0x39, 0x16, 0x17, 0xb0, 0xe8, 0xd9, 0x19, 0x63, 0x53, 0xc6, 0x7a, 0x76, 0xc2, 0xd8,
	0xac, 0xd3, 0xed, 0x4e, 0x9e, 0xb1, 0x79, 0xa7, 0xdb, 0x9d, 0x2c, 0x63, 0xe2, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x26, 0x80, 0x62, 0xc7, 0x57, 0x04, 0x00, 0x00,
}
