// Code generated by protoc-gen-go.
// source: gt_db.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GtDbProtoId int32

const (
	GtDbProtoId_account_role_data_req_id    GtDbProtoId = 1
	GtDbProtoId_account_role_data_ack_id    GtDbProtoId = 2
	GtDbProtoId_db_create_player_of_game_id GtDbProtoId = 3
	GtDbProtoId_db_create_player_ack_id     GtDbProtoId = 4
	GtDbProtoId_db_enter_game_req_id        GtDbProtoId = 5
	GtDbProtoId_db_enter_game_ack_id        GtDbProtoId = 6
	GtDbProtoId_game_player_info_req_id     GtDbProtoId = 7
	GtDbProtoId_game_player_info_ack_id     GtDbProtoId = 8
)

var GtDbProtoId_name = map[int32]string{
	1: "account_role_data_req_id",
	2: "account_role_data_ack_id",
	3: "db_create_player_of_game_id",
	4: "db_create_player_ack_id",
	5: "db_enter_game_req_id",
	6: "db_enter_game_ack_id",
	7: "game_player_info_req_id",
	8: "game_player_info_ack_id",
}
var GtDbProtoId_value = map[string]int32{
	"account_role_data_req_id":    1,
	"account_role_data_ack_id":    2,
	"db_create_player_of_game_id": 3,
	"db_create_player_ack_id":     4,
	"db_enter_game_req_id":        5,
	"db_enter_game_ack_id":        6,
	"game_player_info_req_id":     7,
	"game_player_info_ack_id":     8,
}

func (x GtDbProtoId) Enum() *GtDbProtoId {
	p := new(GtDbProtoId)
	*p = x
	return p
}
func (x GtDbProtoId) String() string {
	return proto.EnumName(GtDbProtoId_name, int32(x))
}
func (x *GtDbProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GtDbProtoId_value, data, "GtDbProtoId")
	if err != nil {
		return err
	}
	*x = GtDbProtoId(value)
	return nil
}
func (GtDbProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type AccountRoleDataReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountRoleDataReq) Reset()                    { *m = AccountRoleDataReq{} }
func (m *AccountRoleDataReq) String() string            { return proto.CompactTextString(m) }
func (*AccountRoleDataReq) ProtoMessage()               {}
func (*AccountRoleDataReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *AccountRoleDataReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AccountRoleDataReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

// role account data ack
type AccountRoleDataAck struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Playerid         *uint64 `protobuf:"varint,4,req,name=playerid" json:"playerid,omitempty"`
	Playername       *string `protobuf:"bytes,5,req,name=playername" json:"playername,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountRoleDataAck) Reset()                    { *m = AccountRoleDataAck{} }
func (m *AccountRoleDataAck) String() string            { return proto.CompactTextString(m) }
func (*AccountRoleDataAck) ProtoMessage()               {}
func (*AccountRoleDataAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *AccountRoleDataAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AccountRoleDataAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *AccountRoleDataAck) GetPlayerid() uint64 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *AccountRoleDataAck) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

// game player info req
type GamePlayerInfoReq struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	GameId           *uint32 `protobuf:"varint,3,req,name=game_id" json:"game_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamePlayerInfoReq) Reset()                    { *m = GamePlayerInfoReq{} }
func (m *GamePlayerInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GamePlayerInfoReq) ProtoMessage()               {}
func (*GamePlayerInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *GamePlayerInfoReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *GamePlayerInfoReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *GamePlayerInfoReq) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

type GamePlayerInfoAck struct {
	Clientid         *uint32 `protobuf:"varint,1,req,name=clientid" json:"clientid,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	GameId           *uint32 `protobuf:"varint,3,req,name=game_id" json:"game_id,omitempty"`
	Playerid         *uint64 `protobuf:"varint,4,req,name=playerid" json:"playerid,omitempty"`
	Playername       *string `protobuf:"bytes,5,req,name=playername" json:"playername,omitempty"`
	Bcanignore       *bool   `protobuf:"varint,6,opt,name=bcanignore" json:"bcanignore,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamePlayerInfoAck) Reset()                    { *m = GamePlayerInfoAck{} }
func (m *GamePlayerInfoAck) String() string            { return proto.CompactTextString(m) }
func (*GamePlayerInfoAck) ProtoMessage()               {}
func (*GamePlayerInfoAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *GamePlayerInfoAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *GamePlayerInfoAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *GamePlayerInfoAck) GetGameId() uint32 {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return 0
}

func (m *GamePlayerInfoAck) GetPlayerid() uint64 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *GamePlayerInfoAck) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *GamePlayerInfoAck) GetBcanignore() bool {
	if m != nil && m.Bcanignore != nil {
		return *m.Bcanignore
	}
	return false
}

// create game
type DbCreatePlayerOfGame struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Playername       *string `protobuf:"bytes,4,req,name=playername" json:"playername,omitempty"`
	Playersex        *int32  `protobuf:"varint,5,req,name=playersex" json:"playersex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbCreatePlayerOfGame) Reset()                    { *m = DbCreatePlayerOfGame{} }
func (m *DbCreatePlayerOfGame) String() string            { return proto.CompactTextString(m) }
func (*DbCreatePlayerOfGame) ProtoMessage()               {}
func (*DbCreatePlayerOfGame) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *DbCreatePlayerOfGame) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *DbCreatePlayerOfGame) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *DbCreatePlayerOfGame) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *DbCreatePlayerOfGame) GetPlayersex() int32 {
	if m != nil && m.Playersex != nil {
		return *m.Playersex
	}
	return 0
}

// create game ack
type DbCreatePlayerAck struct {
	CreateResult *int32  `protobuf:"varint,1,req,name=create_result" json:"create_result,omitempty"`
	Account      *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	Clientid     *uint32 `protobuf:"varint,3,req,name=clientid" json:"clientid,omitempty"`
	// required uint32 gameid = 4;
	Playername       *string `protobuf:"bytes,5,req,name=playername" json:"playername,omitempty"`
	Playerid         *uint64 `protobuf:"varint,6,req,name=playerid" json:"playerid,omitempty"`
	Playersex        *int32  `protobuf:"varint,7,req,name=playersex" json:"playersex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbCreatePlayerAck) Reset()                    { *m = DbCreatePlayerAck{} }
func (m *DbCreatePlayerAck) String() string            { return proto.CompactTextString(m) }
func (*DbCreatePlayerAck) ProtoMessage()               {}
func (*DbCreatePlayerAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *DbCreatePlayerAck) GetCreateResult() int32 {
	if m != nil && m.CreateResult != nil {
		return *m.CreateResult
	}
	return 0
}

func (m *DbCreatePlayerAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *DbCreatePlayerAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *DbCreatePlayerAck) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *DbCreatePlayerAck) GetPlayerid() uint64 {
	if m != nil && m.Playerid != nil {
		return *m.Playerid
	}
	return 0
}

func (m *DbCreatePlayerAck) GetPlayersex() int32 {
	if m != nil && m.Playersex != nil {
		return *m.Playersex
	}
	return 0
}

// enter game
type DbEnterGameReq struct {
	PlayerId         *uint64 `protobuf:"varint,2,req,name=player_id" json:"player_id,omitempty"`
	Account          *string `protobuf:"bytes,3,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,4,req,name=clientid" json:"clientid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbEnterGameReq) Reset()                    { *m = DbEnterGameReq{} }
func (m *DbEnterGameReq) String() string            { return proto.CompactTextString(m) }
func (*DbEnterGameReq) ProtoMessage()               {}
func (*DbEnterGameReq) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *DbEnterGameReq) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *DbEnterGameReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *DbEnterGameReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

type DbEnterGameAck struct {
	EnterRet         *int32  `protobuf:"varint,1,req,name=enter_ret" json:"enter_ret,omitempty"`
	PlayerId         *uint64 `protobuf:"varint,3,req,name=player_id" json:"player_id,omitempty"`
	Clientid         *uint32 `protobuf:"varint,4,req,name=clientid" json:"clientid,omitempty"`
	PlayerName       *string `protobuf:"bytes,5,req,name=player_name" json:"player_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DbEnterGameAck) Reset()                    { *m = DbEnterGameAck{} }
func (m *DbEnterGameAck) String() string            { return proto.CompactTextString(m) }
func (*DbEnterGameAck) ProtoMessage()               {}
func (*DbEnterGameAck) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *DbEnterGameAck) GetEnterRet() int32 {
	if m != nil && m.EnterRet != nil {
		return *m.EnterRet
	}
	return 0
}

func (m *DbEnterGameAck) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *DbEnterGameAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *DbEnterGameAck) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRoleDataReq)(nil), "SProtoSpace.account_role_data_req")
	proto.RegisterType((*AccountRoleDataAck)(nil), "SProtoSpace.account_role_data_ack")
	proto.RegisterType((*GamePlayerInfoReq)(nil), "SProtoSpace.game_player_info_req")
	proto.RegisterType((*GamePlayerInfoAck)(nil), "SProtoSpace.game_player_info_ack")
	proto.RegisterType((*DbCreatePlayerOfGame)(nil), "SProtoSpace.db_create_player_of_game")
	proto.RegisterType((*DbCreatePlayerAck)(nil), "SProtoSpace.db_create_player_ack")
	proto.RegisterType((*DbEnterGameReq)(nil), "SProtoSpace.db_enter_game_req")
	proto.RegisterType((*DbEnterGameAck)(nil), "SProtoSpace.db_enter_game_ack")
	proto.RegisterEnum("SProtoSpace.GtDbProtoId", GtDbProtoId_name, GtDbProtoId_value)
}

func init() { proto.RegisterFile("gt_db.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 406 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdd, 0x4e, 0xc2, 0x30,
	0x14, 0xce, 0xfe, 0x18, 0x1c, 0x82, 0x40, 0x85, 0xd8, 0x88, 0x89, 0xcb, 0xae, 0x16, 0x2f, 0x7c,
	0x00, 0xdf, 0x40, 0xaf, 0x4c, 0x78, 0x80, 0xda, 0xb5, 0x85, 0x34, 0x8c, 0x0d, 0xcb, 0x48, 0xf4,
	0xde, 0x1b, 0xdf, 0xd8, 0x4b, 0xd3, 0x6e, 0xe0, 0xe6, 0x6a, 0x42, 0xbc, 0x5a, 0x72, 0xbe, 0x73,
	0xbe, 0x9f, 0x9e, 0x1d, 0x18, 0xae, 0x4b, 0xc2, 0xd3, 0xfb, 0x9d, 0x2a, 0xca, 0x02, 0x0d, 0x97,
	0xcf, 0xfa, 0xbb, 0xdc, 0x51, 0x26, 0xae, 0x21, 0xa5, 0x7b, 0x51, 0x01, 0xf1, 0x03, 0xcc, 0x29,
	0x63, 0xc5, 0x21, 0x2f, 0x89, 0x2a, 0x32, 0x41, 0x38, 0x2d, 0x29, 0x51, 0xe2, 0x15, 0x8d, 0x21,
	0xac, 0x01, 0xec, 0x44, 0x6e, 0x32, 0x40, 0x13, 0xe8, 0xb3, 0x4c, 0x8a, 0xbc, 0x94, 0x1c, 0xbb,
	0x91, 0x9b, 0x8c, 0xe2, 0x17, 0xdb, 0x2c, 0x65, 0x9b, 0x33, 0x66, 0x75, 0x65, 0x97, 0xd1, 0x77,
	0xa1, 0x24, 0xc7, 0x7e, 0xe4, 0x26, 0x3e, 0x42, 0x00, 0x55, 0x25, 0xa7, 0x5b, 0x81, 0x03, 0x3d,
	0x17, 0x3f, 0xc1, 0x6c, 0x4d, 0xb7, 0x82, 0x54, 0x00, 0x91, 0xf9, 0xaa, 0x30, 0xe6, 0x9a, 0x7c,
	0x8e, 0xe1, 0x6b, 0x48, 0xba, 0x46, 0x72, 0x0c, 0xa1, 0x19, 0x95, 0x1c, 0x7b, 0xc6, 0xed, 0x87,
	0x63, 0x21, 0xd3, 0x6e, 0xff, 0x41, 0x76, 0x9e, 0x7d, 0x5d, 0x4b, 0x19, 0xcd, 0xe5, 0x3a, 0x2f,
	0x94, 0xc0, 0xbd, 0xc8, 0x49, 0xfa, 0x31, 0x07, 0xcc, 0x53, 0xc2, 0x94, 0xa0, 0xe5, 0xc9, 0x4a,
	0xb1, 0x22, 0x9a, 0xfe, 0x9c, 0x77, 0x6b, 0xcb, 0xf8, 0xa6, 0x6b, 0x0a, 0x83, 0xaa, 0xb6, 0x17,
	0x6f, 0x46, 0x39, 0x88, 0x3f, 0x1d, 0x98, 0x75, 0x64, 0x74, 0xd8, 0x39, 0x8c, 0xea, 0xa2, 0x12,
	0xfb, 0x43, 0x56, 0x09, 0x05, 0xdd, 0xc4, 0x4d, 0x65, 0xcf, 0xa2, 0x1c, 0x1c, 0xbb, 0x4e, 0xcf,
	0xd0, 0x33, 0xcf, 0xd0, 0xf2, 0x12, 0x1a, 0x2f, 0x8f, 0x30, 0xe5, 0x29, 0x11, 0x79, 0x29, 0x94,
	0x89, 0x69, 0x36, 0x78, 0xea, 0x23, 0x75, 0x34, 0xbf, 0xe9, 0xc1, 0xeb, 0x78, 0xf0, 0xeb, 0x3f,
	0xee, 0x17, 0x95, 0x8e, 0x34, 0x85, 0x41, 0x55, 0x51, 0xe2, 0x18, 0xa7, 0xc5, 0xee, 0x19, 0xf6,
	0x0e, 0x19, 0xba, 0x84, 0x61, 0xdd, 0xf4, 0x93, 0xe8, 0xee, 0xcb, 0x81, 0x0b, 0x73, 0x38, 0xc4,
	0xdc, 0x07, 0x91, 0x1c, 0xdd, 0x00, 0xb6, 0x9e, 0x08, 0x91, 0x7c, 0xe2, 0xd8, 0x51, 0xca, 0x36,
	0x1a, 0x75, 0xd1, 0x2d, 0x2c, 0xfe, 0xda, 0xb6, 0x6e, 0xf0, 0xd0, 0x02, 0xae, 0x6c, 0x7b, 0xd2,
	0xa0, 0x8f, 0xb0, 0x59, 0x62, 0xfb, 0xe5, 0x34, 0x12, 0x74, 0x91, 0x7a, 0xa6, 0xa7, 0x09, 0x6d,
	0x27, 0xa3, 0xc1, 0xd0, 0x0a, 0xd6, 0x93, 0xfd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x78,
	0xd9, 0xef, 0x31, 0x04, 0x00, 0x00,
}
