// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EAuthType int32

const (
	EAuthType_AUTH_SELF   EAuthType = 0
	EAuthType_AUTH_XIAOMI EAuthType = 1
)

var EAuthType_name = map[int32]string{
	0: "AUTH_SELF",
	1: "AUTH_XIAOMI",
}
var EAuthType_value = map[string]int32{
	"AUTH_SELF":   0,
	"AUTH_XIAOMI": 1,
}

func (x EAuthType) Enum() *EAuthType {
	p := new(EAuthType)
	*p = x
	return p
}
func (x EAuthType) String() string {
	return proto.EnumName(EAuthType_name, int32(x))
}
func (x *EAuthType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EAuthType_value, data, "EAuthType")
	if err != nil {
		return err
	}
	*x = EAuthType(value)
	return nil
}
func (EAuthType) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type ProtoId int32

const (
	ProtoId_LOGIN_REQ_ID              ProtoId = 0
	ProtoId_LOGIN_ACK_ID              ProtoId = 1
	ProtoId_area_list_info_ack_id     ProtoId = 2
	ProtoId_login_need_queued_ntf_id  ProtoId = 3
	ProtoId_login_end_queued_ntf_id   ProtoId = 4
	ProtoId_login_queued_state_req_id ProtoId = 5
	ProtoId_login_queued_state_ack_id ProtoId = 6
	ProtoId_login_cancel_queue_req_id ProtoId = 7
	ProtoId_login_cancel_queue_ack_id ProtoId = 8
	ProtoId_login_error_ntf_id        ProtoId = 9
)

var ProtoId_name = map[int32]string{
	0: "LOGIN_REQ_ID",
	1: "LOGIN_ACK_ID",
	2: "area_list_info_ack_id",
	3: "login_need_queued_ntf_id",
	4: "login_end_queued_ntf_id",
	5: "login_queued_state_req_id",
	6: "login_queued_state_ack_id",
	7: "login_cancel_queue_req_id",
	8: "login_cancel_queue_ack_id",
	9: "login_error_ntf_id",
}
var ProtoId_value = map[string]int32{
	"LOGIN_REQ_ID":              0,
	"LOGIN_ACK_ID":              1,
	"area_list_info_ack_id":     2,
	"login_need_queued_ntf_id":  3,
	"login_end_queued_ntf_id":   4,
	"login_queued_state_req_id": 5,
	"login_queued_state_ack_id": 6,
	"login_cancel_queue_req_id": 7,
	"login_cancel_queue_ack_id": 8,
	"login_error_ntf_id":        9,
}

func (x ProtoId) Enum() *ProtoId {
	p := new(ProtoId)
	*p = x
	return p
}
func (x ProtoId) String() string {
	return proto.EnumName(ProtoId_name, int32(x))
}
func (x *ProtoId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProtoId_value, data, "ProtoId")
	if err != nil {
		return err
	}
	*x = ProtoId(value)
	return nil
}
func (ProtoId) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

// login ack return
type LoginAckError int32

const (
	// unkown error, client care
	LoginAckError_CHECK_ACCOUNT_UNKNOW LoginAckError = -3
	// account error,, client care
	LoginAckError_CHECK_ACCOUNT_INVALID LoginAckError = -2
	// password and user unmatch, client care
	LoginAckError_CHECK_PASSWORD_ERROR LoginAckError = -1
	// ok
	LoginAckError_CHECK_PASSWORD_OK LoginAckError = 0
	// new user ok
	LoginAckError_CHECK_PASSWORD_NEW_USER_OK LoginAckError = 1
	// check ok, client care
	LoginAckError_CHECK_ALL_OK LoginAckError = 2
)

var LoginAckError_name = map[int32]string{
	-3: "CHECK_ACCOUNT_UNKNOW",
	-2: "CHECK_ACCOUNT_INVALID",
	-1: "CHECK_PASSWORD_ERROR",
	0:  "CHECK_PASSWORD_OK",
	1:  "CHECK_PASSWORD_NEW_USER_OK",
	2:  "CHECK_ALL_OK",
}
var LoginAckError_value = map[string]int32{
	"CHECK_ACCOUNT_UNKNOW":       -3,
	"CHECK_ACCOUNT_INVALID":      -2,
	"CHECK_PASSWORD_ERROR":       -1,
	"CHECK_PASSWORD_OK":          0,
	"CHECK_PASSWORD_NEW_USER_OK": 1,
	"CHECK_ALL_OK":               2,
}

func (x LoginAckError) Enum() *LoginAckError {
	p := new(LoginAckError)
	*p = x
	return p
}
func (x LoginAckError) String() string {
	return proto.EnumName(LoginAckError_name, int32(x))
}
func (x *LoginAckError) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LoginAckError_value, data, "LoginAckError")
	if err != nil {
		return err
	}
	*x = LoginAckError(value)
	return nil
}
func (LoginAckError) EnumDescriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

type LoginReq struct {
	Account          *string    `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Password         *string    `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	Isdetail         *bool      `protobuf:"varint,3,opt,name=isdetail" json:"isdetail,omitempty"`
	Userid           *string    `protobuf:"bytes,4,opt,name=userid" json:"userid,omitempty"`
	Usersession      *string    `protobuf:"bytes,5,opt,name=usersession" json:"usersession,omitempty"`
	LoginType        *EAuthType `protobuf:"varint,6,opt,name=loginType,enum=SProtoSpace.EAuthType" json:"loginType,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *LoginReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *LoginReq) GetIsdetail() bool {
	if m != nil && m.Isdetail != nil {
		return *m.Isdetail
	}
	return false
}

func (m *LoginReq) GetUserid() string {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return ""
}

func (m *LoginReq) GetUsersession() string {
	if m != nil && m.Usersession != nil {
		return *m.Usersession
	}
	return ""
}

func (m *LoginReq) GetLoginType() EAuthType {
	if m != nil && m.LoginType != nil {
		return *m.LoginType
	}
	return EAuthType_AUTH_SELF
}

type LoginAck struct {
	Ret              *int32 `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginAck) Reset()                    { *m = LoginAck{} }
func (m *LoginAck) String() string            { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()               {}
func (*LoginAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *LoginAck) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

type AreaListInfoAck struct {
	// group net info
	GroupNetInfo []*GateNetInfo `protobuf:"bytes,1,rep,name=group_net_info" json:"group_net_info,omitempty"`
	// account return
	Account *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	// check center server id
	CheckServerId    *uint64          `protobuf:"varint,3,opt,name=check_server_id" json:"check_server_id,omitempty"`
	AreaGroups       []*GroupAreaInfo `protobuf:"bytes,4,rep,name=area_groups" json:"area_groups,omitempty"`
	RecommendAreas   []*GroupAreaInfo `protobuf:"bytes,5,rep,name=recommend_areas" json:"recommend_areas,omitempty"`
	MyLoginAreas     *GroupAreaInfo   `protobuf:"bytes,6,opt,name=my_login_areas" json:"my_login_areas,omitempty"`
	MyGroupPlayers   []*GroupHeroInfo `protobuf:"bytes,7,rep,name=my_group_players" json:"my_group_players,omitempty"`
	Token            *int32           `protobuf:"varint,8,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AreaListInfoAck) Reset()                    { *m = AreaListInfoAck{} }
func (m *AreaListInfoAck) String() string            { return proto.CompactTextString(m) }
func (*AreaListInfoAck) ProtoMessage()               {}
func (*AreaListInfoAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func (m *AreaListInfoAck) GetGroupNetInfo() []*GateNetInfo {
	if m != nil {
		return m.GroupNetInfo
	}
	return nil
}

func (m *AreaListInfoAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AreaListInfoAck) GetCheckServerId() uint64 {
	if m != nil && m.CheckServerId != nil {
		return *m.CheckServerId
	}
	return 0
}

func (m *AreaListInfoAck) GetAreaGroups() []*GroupAreaInfo {
	if m != nil {
		return m.AreaGroups
	}
	return nil
}

func (m *AreaListInfoAck) GetRecommendAreas() []*GroupAreaInfo {
	if m != nil {
		return m.RecommendAreas
	}
	return nil
}

func (m *AreaListInfoAck) GetMyLoginAreas() *GroupAreaInfo {
	if m != nil {
		return m.MyLoginAreas
	}
	return nil
}

func (m *AreaListInfoAck) GetMyGroupPlayers() []*GroupHeroInfo {
	if m != nil {
		return m.MyGroupPlayers
	}
	return nil
}

func (m *AreaListInfoAck) GetToken() int32 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

type LoginNeedQueuedNtf struct {
	Pos              *uint32 `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginNeedQueuedNtf) Reset()                    { *m = LoginNeedQueuedNtf{} }
func (m *LoginNeedQueuedNtf) String() string            { return proto.CompactTextString(m) }
func (*LoginNeedQueuedNtf) ProtoMessage()               {}
func (*LoginNeedQueuedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{3} }

func (m *LoginNeedQueuedNtf) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type LoginEndQueuedNtf struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginEndQueuedNtf) Reset()                    { *m = LoginEndQueuedNtf{} }
func (m *LoginEndQueuedNtf) String() string            { return proto.CompactTextString(m) }
func (*LoginEndQueuedNtf) ProtoMessage()               {}
func (*LoginEndQueuedNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{4} }

type LoginQueuedStateReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginQueuedStateReq) Reset()                    { *m = LoginQueuedStateReq{} }
func (m *LoginQueuedStateReq) String() string            { return proto.CompactTextString(m) }
func (*LoginQueuedStateReq) ProtoMessage()               {}
func (*LoginQueuedStateReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{5} }

type LoginQueuedStateAck struct {
	Pos              *uint32 `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginQueuedStateAck) Reset()                    { *m = LoginQueuedStateAck{} }
func (m *LoginQueuedStateAck) String() string            { return proto.CompactTextString(m) }
func (*LoginQueuedStateAck) ProtoMessage()               {}
func (*LoginQueuedStateAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{6} }

func (m *LoginQueuedStateAck) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type LoginCancelQueueReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginCancelQueueReq) Reset()                    { *m = LoginCancelQueueReq{} }
func (m *LoginCancelQueueReq) String() string            { return proto.CompactTextString(m) }
func (*LoginCancelQueueReq) ProtoMessage()               {}
func (*LoginCancelQueueReq) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{7} }

type LoginCancelQueueAck struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginCancelQueueAck) Reset()                    { *m = LoginCancelQueueAck{} }
func (m *LoginCancelQueueAck) String() string            { return proto.CompactTextString(m) }
func (*LoginCancelQueueAck) ProtoMessage()               {}
func (*LoginCancelQueueAck) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{8} }

type LoginErrorNtf struct {
	ErrorNum         *int32 `protobuf:"varint,1,req,name=error_num" json:"error_num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LoginErrorNtf) Reset()                    { *m = LoginErrorNtf{} }
func (m *LoginErrorNtf) String() string            { return proto.CompactTextString(m) }
func (*LoginErrorNtf) ProtoMessage()               {}
func (*LoginErrorNtf) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{9} }

func (m *LoginErrorNtf) GetErrorNum() int32 {
	if m != nil && m.ErrorNum != nil {
		return *m.ErrorNum
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "SProtoSpace.login_req")
	proto.RegisterType((*LoginAck)(nil), "SProtoSpace.login_ack")
	proto.RegisterType((*AreaListInfoAck)(nil), "SProtoSpace.area_list_info_ack")
	proto.RegisterType((*LoginNeedQueuedNtf)(nil), "SProtoSpace.login_need_queued_ntf")
	proto.RegisterType((*LoginEndQueuedNtf)(nil), "SProtoSpace.login_end_queued_ntf")
	proto.RegisterType((*LoginQueuedStateReq)(nil), "SProtoSpace.login_queued_state_req")
	proto.RegisterType((*LoginQueuedStateAck)(nil), "SProtoSpace.login_queued_state_ack")
	proto.RegisterType((*LoginCancelQueueReq)(nil), "SProtoSpace.login_cancel_queue_req")
	proto.RegisterType((*LoginCancelQueueAck)(nil), "SProtoSpace.login_cancel_queue_ack")
	proto.RegisterType((*LoginErrorNtf)(nil), "SProtoSpace.login_error_ntf")
	proto.RegisterEnum("SProtoSpace.EAuthType", EAuthType_name, EAuthType_value)
	proto.RegisterEnum("SProtoSpace.ProtoId", ProtoId_name, ProtoId_value)
	proto.RegisterEnum("SProtoSpace.LoginAckError", LoginAckError_name, LoginAckError_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xf3, 0xd3, 0xc4, 0xe3, 0xaf, 0x89, 0xbb, 0x5f, 0x93, 0x6e, 0xfb, 0xf5, 0x43, 0xc1,
	0x2a, 0x52, 0x28, 0x52, 0x25, 0x2a, 0xe0, 0xde, 0x4a, 0x0d, 0xb5, 0x12, 0xe2, 0x92, 0x34, 0x94,
	0xbb, 0x95, 0xb1, 0xb7, 0xad, 0x95, 0xc4, 0x76, 0x77, 0x6d, 0x50, 0xde, 0x82, 0x3b, 0x5e, 0x88,
	0x97, 0xe0, 0x61, 0xa0, 0x68, 0xd7, 0x6e, 0xd2, 0x86, 0x54, 0x90, 0x9b, 0x68, 0xcf, 0x39, 0x33,
	0x67, 0xe6, 0xec, 0x1a, 0xb4, 0x49, 0x74, 0x19, 0x84, 0x87, 0x31, 0x8b, 0x92, 0x08, 0x69, 0xc3,
	0x53, 0xf1, 0x3f, 0x8c, 0x5d, 0x8f, 0xee, 0xc2, 0x47, 0x97, 0xd3, 0x8c, 0x30, 0xbe, 0x28, 0xa0,
	0x4a, 0x21, 0x61, 0xf4, 0x1a, 0xd5, 0xa1, 0xe2, 0x7a, 0x5e, 0x94, 0x86, 0x09, 0x56, 0x5a, 0x85,
	0xb6, 0x8a, 0x74, 0xa8, 0xc6, 0x2e, 0xe7, 0x9f, 0x23, 0xe6, 0xe3, 0xc2, 0x2d, 0x12, 0x70, 0x9f,
	0x26, 0x6e, 0x30, 0xc1, 0xc5, 0x96, 0xd2, 0xae, 0xa2, 0x1a, 0xac, 0xa7, 0x9c, 0xb2, 0xc0, 0xc7,
	0xa5, 0x96, 0xd2, 0x56, 0xd1, 0xbf, 0xa0, 0x89, 0x33, 0xa7, 0x9c, 0x07, 0x51, 0x88, 0xcb, 0x12,
	0x7c, 0x9a, 0xdb, 0x9c, 0xcd, 0x62, 0x8a, 0xd7, 0x5b, 0x4a, 0xbb, 0x76, 0xd4, 0x3c, 0xbc, 0x33,
	0xd4, 0xa1, 0x65, 0xa6, 0xc9, 0x95, 0x60, 0x0d, 0x7c, 0x3b, 0x91, 0xeb, 0x8d, 0x91, 0x06, 0x45,
	0x46, 0xb3, 0x69, 0xca, 0xc6, 0xf7, 0x02, 0x20, 0x97, 0x51, 0x97, 0x4c, 0x02, 0x9e, 0x90, 0x20,
	0xbc, 0x88, 0xa4, 0xe6, 0x08, 0x6a, 0x97, 0x2c, 0x4a, 0x63, 0x12, 0xd2, 0x0c, 0xc5, 0x4a, 0xab,
	0xd8, 0xd6, 0x8e, 0x76, 0xef, 0x19, 0x5c, 0xba, 0x09, 0x9d, 0x2b, 0xee, 0x6e, 0x9a, 0xed, 0xb5,
	0x0d, 0x75, 0xef, 0x8a, 0x7a, 0x63, 0xc2, 0x29, 0xfb, 0x44, 0x19, 0x09, 0x7c, 0xb9, 0x5e, 0x09,
	0x3d, 0x07, 0x4d, 0x7a, 0x4a, 0x0b, 0x8e, 0x4b, 0xb2, 0xf5, 0xde, 0xfd, 0xd6, 0xd2, 0x5d, 0xaa,
	0x64, 0xf3, 0x97, 0x50, 0x67, 0xd4, 0x8b, 0xa6, 0x53, 0x1a, 0xfa, 0x12, 0xe6, 0xb8, 0xfc, 0x17,
	0x65, 0x2f, 0xa0, 0x36, 0x9d, 0x91, 0x7c, 0x77, 0x59, 0x25, 0x82, 0xfa, 0x53, 0xd5, 0x2b, 0xd0,
	0xa7, 0xb3, 0x6c, 0x3a, 0x12, 0x4f, 0xdc, 0x19, 0x65, 0x1c, 0x57, 0x1e, 0x74, 0xbb, 0xa2, 0x2c,
	0xca, 0xea, 0x36, 0xa0, 0x9c, 0x44, 0x63, 0x1a, 0xe2, 0xaa, 0xcc, 0x76, 0x1f, 0x1a, 0x99, 0x73,
	0x48, 0xa9, 0x4f, 0xae, 0x53, 0x9a, 0x52, 0x9f, 0x84, 0xc9, 0x85, 0xb8, 0x81, 0x38, 0xe2, 0xf2,
	0x06, 0x36, 0x8c, 0x26, 0x6c, 0x65, 0x2a, 0xb1, 0xd9, 0x42, 0x64, 0x60, 0x68, 0x66, 0x78, 0x8e,
	0xf1, 0x44, 0xa4, 0xcd, 0xe8, 0xb5, 0xf1, 0x64, 0x25, 0x93, 0x5f, 0xed, 0xa2, 0xf1, 0xbc, 0x81,
	0xe7, 0x86, 0x1e, 0x9d, 0x64, 0x6a, 0xd9, 0x60, 0x35, 0xe3, 0x7a, 0x63, 0x63, 0x1f, 0xea, 0xf9,
	0x30, 0x8c, 0x45, 0x4c, 0x0e, 0xbb, 0x09, 0x6a, 0x7e, 0x48, 0xa7, 0xd9, 0xa3, 0x39, 0x78, 0x06,
	0xea, 0xfc, 0x6d, 0xa1, 0x0d, 0x50, 0xcd, 0xd1, 0xd9, 0x09, 0x19, 0x5a, 0xbd, 0xd7, 0xfa, 0x1a,
	0xaa, 0x83, 0x26, 0x8f, 0x1f, 0x6c, 0xd3, 0x79, 0x6b, 0xeb, 0xca, 0xc1, 0xd7, 0x02, 0x54, 0xe4,
	0x87, 0x61, 0xfb, 0x48, 0x87, 0x7f, 0x7a, 0xce, 0x1b, 0xbb, 0x4f, 0x06, 0xd6, 0x3b, 0x62, 0x1f,
	0xeb, 0x6b, 0x0b, 0xc4, 0xec, 0x74, 0x05, 0xa2, 0xa0, 0x1d, 0x68, 0xfc, 0xfe, 0x20, 0x49, 0xe0,
	0xeb, 0x05, 0xb4, 0x07, 0x78, 0x65, 0xa0, 0x82, 0x2d, 0xa2, 0xff, 0x60, 0x7b, 0x55, 0x90, 0x82,
	0x2c, 0xa1, 0xff, 0x61, 0x67, 0x75, 0x9a, 0x82, 0x2e, 0x3f, 0x40, 0xe7, 0xc6, 0xeb, 0x0b, 0x7a,
	0x39, 0x4a, 0x41, 0x57, 0x1e, 0xa0, 0xf3, 0xea, 0x2a, 0x6a, 0x02, 0x5a, 0x0a, 0x55, 0xe0, 0xea,
	0xc1, 0x37, 0xe5, 0x36, 0x6d, 0x21, 0x95, 0x24, 0x7a, 0x0c, 0x5b, 0x9d, 0x13, 0xab, 0xd3, 0x25,
	0x66, 0xa7, 0xe3, 0x8c, 0xfa, 0x67, 0x64, 0xd4, 0xef, 0xf6, 0x9d, 0x73, 0xfd, 0xc7, 0x4d, 0xfe,
	0x53, 0x90, 0x01, 0x8d, 0xfb, 0x12, 0xbb, 0xff, 0xde, 0xec, 0xd9, 0xc7, 0xfa, 0xcf, 0x85, 0x66,
	0xde, 0xe6, 0xd4, 0x1c, 0x0e, 0xcf, 0x9d, 0xc1, 0x31, 0xb1, 0x06, 0x03, 0x67, 0xa0, 0xdf, 0x2c,
	0x24, 0x0d, 0xd8, 0x5c, 0x92, 0x38, 0x5d, 0x7d, 0x0d, 0x3d, 0x82, 0xdd, 0x25, 0xb8, 0x6f, 0x9d,
	0x93, 0xd1, 0xd0, 0x1a, 0x08, 0x5e, 0x11, 0x17, 0x96, 0xbb, 0xf7, 0x7a, 0x02, 0x29, 0xfc, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0xa8, 0xff, 0xd3, 0x19, 0x16, 0x05, 0x00, 0x00,
}
