// Code generated by protoc-gen-go.
// source: ls_center.proto
// DO NOT EDIT!

package SProtoSpace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EPropId int32

const (
	EPropId_area_list_req_id EPropId = 1
	EPropId_area_list_ack_id EPropId = 2
)

var EPropId_name = map[int32]string{
	1: "area_list_req_id",
	2: "area_list_ack_id",
}
var EPropId_value = map[string]int32{
	"area_list_req_id": 1,
	"area_list_ack_id": 2,
}

func (x EPropId) Enum() *EPropId {
	p := new(EPropId)
	*p = x
	return p
}
func (x EPropId) String() string {
	return proto.EnumName(EPropId_name, int32(x))
}
func (x *EPropId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EPropId_value, data, "EPropId")
	if err != nil {
		return err
	}
	*x = EPropId(value)
	return nil
}
func (EPropId) EnumDescriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

type AreaListReq struct {
	Account          *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32 `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AreaListReq) Reset()                    { *m = AreaListReq{} }
func (m *AreaListReq) String() string            { return proto.CompactTextString(m) }
func (*AreaListReq) ProtoMessage()               {}
func (*AreaListReq) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *AreaListReq) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AreaListReq) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

type AreaListAck struct {
	Account          *string          `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
	Clientid         *uint32          `protobuf:"varint,2,req,name=clientid" json:"clientid,omitempty"`
	Groups           []*GateNetInfo   `protobuf:"bytes,3,rep,name=groups" json:"groups,omitempty"`
	Centerid         *uint64          `protobuf:"varint,4,opt,name=centerid" json:"centerid,omitempty"`
	AreaGroups       []*GroupAreaInfo `protobuf:"bytes,5,rep,name=area_groups" json:"area_groups,omitempty"`
	RecommendAreas   []*GroupAreaInfo `protobuf:"bytes,6,rep,name=recommend_areas" json:"recommend_areas,omitempty"`
	Token            *int32           `protobuf:"varint,7,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AreaListAck) Reset()                    { *m = AreaListAck{} }
func (m *AreaListAck) String() string            { return proto.CompactTextString(m) }
func (*AreaListAck) ProtoMessage()               {}
func (*AreaListAck) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *AreaListAck) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AreaListAck) GetClientid() uint32 {
	if m != nil && m.Clientid != nil {
		return *m.Clientid
	}
	return 0
}

func (m *AreaListAck) GetGroups() []*GateNetInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *AreaListAck) GetCenterid() uint64 {
	if m != nil && m.Centerid != nil {
		return *m.Centerid
	}
	return 0
}

func (m *AreaListAck) GetAreaGroups() []*GroupAreaInfo {
	if m != nil {
		return m.AreaGroups
	}
	return nil
}

func (m *AreaListAck) GetRecommendAreas() []*GroupAreaInfo {
	if m != nil {
		return m.RecommendAreas
	}
	return nil
}

func (m *AreaListAck) GetToken() int32 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func init() {
	proto.RegisterType((*AreaListReq)(nil), "SProtoSpace.area_list_req")
	proto.RegisterType((*AreaListAck)(nil), "SProtoSpace.area_list_ack")
	proto.RegisterEnum("SProtoSpace.EPropId", EPropId_name, EPropId_value)
}

func init() { proto.RegisterFile("ls_center.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x6a, 0xc3, 0x20,
	0x1c, 0xc6, 0x89, 0x6d, 0x9a, 0xed, 0x1f, 0x42, 0x82, 0xec, 0x20, 0x65, 0x07, 0xe9, 0x49, 0x7a,
	0x08, 0xac, 0xd0, 0x87, 0xd8, 0xad, 0xd0, 0x07, 0x10, 0xa7, 0xff, 0x15, 0x49, 0xaa, 0x99, 0xda,
	0x87, 0xde, 0x5b, 0x8c, 0xb8, 0x1e, 0x9a, 0x5b, 0x4f, 0xc2, 0xf7, 0xf9, 0xfb, 0xf9, 0x21, 0xb4,
	0x63, 0x94, 0x1a, 0x5d, 0xc2, 0xd0, 0x4f, 0xc1, 0x27, 0x4f, 0xeb, 0xf3, 0x69, 0x3e, 0xcf, 0x93,
	0xd2, 0xb8, 0x85, 0x2f, 0x15, 0xf1, 0xbf, 0xd8, 0x1d, 0xa0, 0x51, 0x01, 0x95, 0x1c, 0x6d, 0x4c,
	0x32, 0xe0, 0x0f, 0x6d, 0xa1, 0x52, 0x5a, 0xfb, 0x9b, 0x4b, 0xac, 0xe0, 0x44, 0xbc, 0xd2, 0x0e,
	0x5e, 0xf4, 0x68, 0xd1, 0x25, 0x6b, 0x18, 0xe1, 0x44, 0x34, 0xbb, 0xdf, 0xe2, 0x11, 0x52, 0x7a,
	0x78, 0x02, 0xa2, 0x7b, 0xd8, 0x5c, 0x82, 0xbf, 0x4d, 0x91, 0xad, 0xf8, 0x4a, 0xd4, 0x87, 0x6d,
	0xff, 0x30, 0xa9, 0xbf, 0xa8, 0x84, 0xd2, 0x61, 0x92, 0xd6, 0x7d, 0xfb, 0x4c, 0xe7, 0xf5, 0xd6,
	0xb0, 0x35, 0x2f, 0xc4, 0x9a, 0x7e, 0x40, 0x9d, 0x5f, 0xbc, 0x2b, 0xca, 0xac, 0x78, 0x5f, 0x2a,
	0xe6, 0x4a, 0xe6, 0x5b, 0x59, 0x72, 0x84, 0x36, 0xa0, 0xf6, 0xd7, 0x2b, 0x3a, 0x93, 0xe3, 0xc8,
	0x36, 0x4f, 0x60, 0x0d, 0x94, 0xc9, 0x0f, 0xe8, 0x58, 0xc5, 0x89, 0x28, 0xf7, 0x47, 0xa8, 0xf0,
	0x14, 0xfc, 0xf4, 0x69, 0xe8, 0x1b, 0x74, 0x8b, 0xaf, 0x92, 0xd6, 0x74, 0xc5, 0x32, 0x55, 0x7a,
	0x98, 0x53, 0xf2, 0x17, 0x00, 0x00, 0xff, 0xff, 0x46, 0x99, 0x94, 0xac, 0x81, 0x01, 0x00, 0x00,
}
