# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gs_gt.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gs_gt.proto',
  package='SProtoSpace',
  serialized_pb='\n\x0bgs_gt.proto\x12\x0bSProtoSpace\x1a\nbase.proto\"\x7f\n\x18player_enter_game_server\x12\x11\n\tplayer_id\x18\x01 \x02(\x04\x12\x13\n\x0bplayer_name\x18\x02 \x02(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x02(\t\x12\x15\n\rnotify_client\x18\x04 \x02(\x05\x12\x13\n\x0b\x64\x62server_id\x18\x05 \x02(\x04\"!\n\x10gs_broadcast_req\x12\r\n\x05proto\x18\x02 \x02(\x0c\"8\n\x12gs_change_name_req\x12\x10\n\x08new_name\x18\x01 \x02(\t\x12\x10\n\x08old_name\x18\x02 \x02(\t\"&\n\x12gt_change_name_ret\x12\x10\n\x08new_name\x18\x01 \x02(\t\"\x1b\n\x19gs_jump_to_cross_game_req\"5\n\x10gs_kick_role_ntf\x12\x11\n\tplayer_id\x18\x01 \x02(\x04\x12\x0e\n\x06reason\x18\x02 \x02(\x05\"\'\n\x11gs_player_num_ntf\x12\x12\n\nplayer_num\x18\x01 \x02(\r\"\x13\n\x11gt_db_msg_forward\"\x1d\n\x1bgs_forward_client_msg_to_gt\"\x1d\n\x1bgt_forward_client_msg_to_gs\"Q\n\x18gt_create_player_of_game\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08\x63lientid\x18\x02 \x02(\r\x12\x12\n\nplayername\x18\x04 \x02(\t\"v\n\x14gs_create_player_ack\x12\x15\n\rcreate_result\x18\x01 \x02(\x05\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x02(\t\x12\x10\n\x08\x63lientid\x18\x03 \x02(\r\x12\x12\n\nplayername\x18\x05 \x02(\t\x12\x10\n\x08playerid\x18\x06 \x02(\x04*\x8c\x03\n\x08\x65ProtoId\x12\x1f\n\x1bplayer_enter_game_server_id\x10\x02\x12\x17\n\x13gs_broadcast_req_id\x10\x03\x12\x19\n\x15gs_change_name_req_id\x10\x04\x12\x19\n\x15gt_change_name_ret_id\x10\x05\x12 \n\x1cgs_jump_to_cross_game_req_id\x10\x06\x12\x17\n\x13gs_kick_role_ntf_id\x10\x07\x12\x18\n\x14gs_player_num_ntf_id\x10\x08\x12\x18\n\x14gt_db_msg_forward_id\x10\t\x12\"\n\x1egs_forward_client_msg_to_gt_id\x10\n\x12\"\n\x1egt_forward_client_msg_to_gs_id\x10\x0b\x12\x1f\n\x1bgt_create_player_of_game_id\x10\x0c\x12\x1b\n\x17gs_create_player_ack_id\x10\r\x12\x1b\n\x17gt_gs_leave_game_req_id\x10\x0e')

_EPROTOID = _descriptor.EnumDescriptor(
  name='eProtoId',
  full_name='SProtoSpace.eProtoId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='player_enter_game_server_id', index=0, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_broadcast_req_id', index=1, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_change_name_req_id', index=2, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gt_change_name_ret_id', index=3, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_jump_to_cross_game_req_id', index=4, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_kick_role_ntf_id', index=5, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_player_num_ntf_id', index=6, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gt_db_msg_forward_id', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_forward_client_msg_to_gt_id', index=8, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gt_forward_client_msg_to_gs_id', index=9, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gt_create_player_of_game_id', index=10, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gs_create_player_ack_id', index=11, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='gt_gs_leave_game_req_id', index=12, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=714,
  serialized_end=1110,
)

eProtoId = enum_type_wrapper.EnumTypeWrapper(_EPROTOID)
player_enter_game_server_id = 2
gs_broadcast_req_id = 3
gs_change_name_req_id = 4
gt_change_name_ret_id = 5
gs_jump_to_cross_game_req_id = 6
gs_kick_role_ntf_id = 7
gs_player_num_ntf_id = 8
gt_db_msg_forward_id = 9
gs_forward_client_msg_to_gt_id = 10
gt_forward_client_msg_to_gs_id = 11
gt_create_player_of_game_id = 12
gs_create_player_ack_id = 13
gt_gs_leave_game_req_id = 14



_PLAYER_ENTER_GAME_SERVER = _descriptor.Descriptor(
  name='player_enter_game_server',
  full_name='SProtoSpace.player_enter_game_server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SProtoSpace.player_enter_game_server.player_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='SProtoSpace.player_enter_game_server.player_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.player_enter_game_server.account', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_client', full_name='SProtoSpace.player_enter_game_server.notify_client', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dbserver_id', full_name='SProtoSpace.player_enter_game_server.dbserver_id', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=167,
)


_GS_BROADCAST_REQ = _descriptor.Descriptor(
  name='gs_broadcast_req',
  full_name='SProtoSpace.gs_broadcast_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proto', full_name='SProtoSpace.gs_broadcast_req.proto', index=0,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=202,
)


_GS_CHANGE_NAME_REQ = _descriptor.Descriptor(
  name='gs_change_name_req',
  full_name='SProtoSpace.gs_change_name_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_name', full_name='SProtoSpace.gs_change_name_req.new_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='old_name', full_name='SProtoSpace.gs_change_name_req.old_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=260,
)


_GT_CHANGE_NAME_RET = _descriptor.Descriptor(
  name='gt_change_name_ret',
  full_name='SProtoSpace.gt_change_name_ret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_name', full_name='SProtoSpace.gt_change_name_ret.new_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=262,
  serialized_end=300,
)


_GS_JUMP_TO_CROSS_GAME_REQ = _descriptor.Descriptor(
  name='gs_jump_to_cross_game_req',
  full_name='SProtoSpace.gs_jump_to_cross_game_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=302,
  serialized_end=329,
)


_GS_KICK_ROLE_NTF = _descriptor.Descriptor(
  name='gs_kick_role_ntf',
  full_name='SProtoSpace.gs_kick_role_ntf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SProtoSpace.gs_kick_role_ntf.player_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='SProtoSpace.gs_kick_role_ntf.reason', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=384,
)


_GS_PLAYER_NUM_NTF = _descriptor.Descriptor(
  name='gs_player_num_ntf',
  full_name='SProtoSpace.gs_player_num_ntf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_num', full_name='SProtoSpace.gs_player_num_ntf.player_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=386,
  serialized_end=425,
)


_GT_DB_MSG_FORWARD = _descriptor.Descriptor(
  name='gt_db_msg_forward',
  full_name='SProtoSpace.gt_db_msg_forward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=427,
  serialized_end=446,
)


_GS_FORWARD_CLIENT_MSG_TO_GT = _descriptor.Descriptor(
  name='gs_forward_client_msg_to_gt',
  full_name='SProtoSpace.gs_forward_client_msg_to_gt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=448,
  serialized_end=477,
)


_GT_FORWARD_CLIENT_MSG_TO_GS = _descriptor.Descriptor(
  name='gt_forward_client_msg_to_gs',
  full_name='SProtoSpace.gt_forward_client_msg_to_gs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=479,
  serialized_end=508,
)


_GT_CREATE_PLAYER_OF_GAME = _descriptor.Descriptor(
  name='gt_create_player_of_game',
  full_name='SProtoSpace.gt_create_player_of_game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.gt_create_player_of_game.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.gt_create_player_of_game.clientid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playername', full_name='SProtoSpace.gt_create_player_of_game.playername', index=2,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=510,
  serialized_end=591,
)


_GS_CREATE_PLAYER_ACK = _descriptor.Descriptor(
  name='gs_create_player_ack',
  full_name='SProtoSpace.gs_create_player_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='create_result', full_name='SProtoSpace.gs_create_player_ack.create_result', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.gs_create_player_ack.account', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.gs_create_player_ack.clientid', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playername', full_name='SProtoSpace.gs_create_player_ack.playername', index=3,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerid', full_name='SProtoSpace.gs_create_player_ack.playerid', index=4,
      number=6, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=593,
  serialized_end=711,
)

DESCRIPTOR.message_types_by_name['player_enter_game_server'] = _PLAYER_ENTER_GAME_SERVER
DESCRIPTOR.message_types_by_name['gs_broadcast_req'] = _GS_BROADCAST_REQ
DESCRIPTOR.message_types_by_name['gs_change_name_req'] = _GS_CHANGE_NAME_REQ
DESCRIPTOR.message_types_by_name['gt_change_name_ret'] = _GT_CHANGE_NAME_RET
DESCRIPTOR.message_types_by_name['gs_jump_to_cross_game_req'] = _GS_JUMP_TO_CROSS_GAME_REQ
DESCRIPTOR.message_types_by_name['gs_kick_role_ntf'] = _GS_KICK_ROLE_NTF
DESCRIPTOR.message_types_by_name['gs_player_num_ntf'] = _GS_PLAYER_NUM_NTF
DESCRIPTOR.message_types_by_name['gt_db_msg_forward'] = _GT_DB_MSG_FORWARD
DESCRIPTOR.message_types_by_name['gs_forward_client_msg_to_gt'] = _GS_FORWARD_CLIENT_MSG_TO_GT
DESCRIPTOR.message_types_by_name['gt_forward_client_msg_to_gs'] = _GT_FORWARD_CLIENT_MSG_TO_GS
DESCRIPTOR.message_types_by_name['gt_create_player_of_game'] = _GT_CREATE_PLAYER_OF_GAME
DESCRIPTOR.message_types_by_name['gs_create_player_ack'] = _GS_CREATE_PLAYER_ACK

class player_enter_game_server(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLAYER_ENTER_GAME_SERVER

  # @@protoc_insertion_point(class_scope:SProtoSpace.player_enter_game_server)

class gs_broadcast_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_BROADCAST_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_broadcast_req)

class gs_change_name_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_CHANGE_NAME_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_change_name_req)

class gt_change_name_ret(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GT_CHANGE_NAME_RET

  # @@protoc_insertion_point(class_scope:SProtoSpace.gt_change_name_ret)

class gs_jump_to_cross_game_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_JUMP_TO_CROSS_GAME_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_jump_to_cross_game_req)

class gs_kick_role_ntf(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_KICK_ROLE_NTF

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_kick_role_ntf)

class gs_player_num_ntf(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_PLAYER_NUM_NTF

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_player_num_ntf)

class gt_db_msg_forward(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GT_DB_MSG_FORWARD

  # @@protoc_insertion_point(class_scope:SProtoSpace.gt_db_msg_forward)

class gs_forward_client_msg_to_gt(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_FORWARD_CLIENT_MSG_TO_GT

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_forward_client_msg_to_gt)

class gt_forward_client_msg_to_gs(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GT_FORWARD_CLIENT_MSG_TO_GS

  # @@protoc_insertion_point(class_scope:SProtoSpace.gt_forward_client_msg_to_gs)

class gt_create_player_of_game(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GT_CREATE_PLAYER_OF_GAME

  # @@protoc_insertion_point(class_scope:SProtoSpace.gt_create_player_of_game)

class gs_create_player_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GS_CREATE_PLAYER_ACK

  # @@protoc_insertion_point(class_scope:SProtoSpace.gs_create_player_ack)


# @@protoc_insertion_point(module_scope)
