# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gt_db.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gt_db.proto',
  package='SProtoSpace',
  serialized_pb='\n\x0bgt_db.proto\x12\x0bSProtoSpace\x1a\nbase.proto\":\n\x15\x61\x63\x63ount_role_data_req\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08\x63lientid\x18\x02 \x02(\r\"`\n\x15\x61\x63\x63ount_role_data_ack\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08\x63lientid\x18\x02 \x02(\r\x12\x10\n\x08playerid\x18\x04 \x02(\x04\x12\x12\n\nplayername\x18\x05 \x02(\t\"J\n\x14game_player_info_req\x12\x10\n\x08\x63lientid\x18\x01 \x02(\r\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x02(\t\x12\x0f\n\x07game_id\x18\x03 \x02(\r\"\x84\x01\n\x14game_player_info_ack\x12\x10\n\x08\x63lientid\x18\x01 \x02(\r\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x02(\t\x12\x0f\n\x07game_id\x18\x03 \x02(\r\x12\x10\n\x08playerid\x18\x04 \x02(\x04\x12\x12\n\nplayername\x18\x05 \x02(\t\x12\x12\n\nbcanignore\x18\x06 \x01(\x08\"I\n\x11\x64\x62_enter_game_req\x12\x11\n\tplayer_id\x18\x02 \x02(\x04\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x02(\t\x12\x10\n\x08\x63lientid\x18\x04 \x02(\r\"`\n\x11\x64\x62_enter_game_ack\x12\x11\n\tenter_ret\x18\x01 \x02(\x05\x12\x11\n\tplayer_id\x18\x03 \x02(\x04\x12\x10\n\x08\x63lientid\x18\x04 \x02(\r\x12\x13\n\x0bplayer_name\x18\x05 \x02(\t*\xba\x01\n\x0egt_db_proto_id\x12\x1c\n\x18\x61\x63\x63ount_role_data_req_id\x10\x01\x12\x1c\n\x18\x61\x63\x63ount_role_data_ack_id\x10\x02\x12\x18\n\x14\x64\x62_enter_game_req_id\x10\x05\x12\x18\n\x14\x64\x62_enter_game_ack_id\x10\x06\x12\x1b\n\x17game_player_info_req_id\x10\x07\x12\x1b\n\x17game_player_info_ack_id\x10\x08')

_GT_DB_PROTO_ID = _descriptor.EnumDescriptor(
  name='gt_db_proto_id',
  full_name='SProtoSpace.gt_db_proto_id',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='account_role_data_req_id', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='account_role_data_ack_id', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='db_enter_game_req_id', index=2, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='db_enter_game_ack_id', index=3, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='game_player_info_req_id', index=4, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='game_player_info_ack_id', index=5, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=583,
  serialized_end=769,
)

gt_db_proto_id = enum_type_wrapper.EnumTypeWrapper(_GT_DB_PROTO_ID)
account_role_data_req_id = 1
account_role_data_ack_id = 2
db_enter_game_req_id = 5
db_enter_game_ack_id = 6
game_player_info_req_id = 7
game_player_info_ack_id = 8



_ACCOUNT_ROLE_DATA_REQ = _descriptor.Descriptor(
  name='account_role_data_req',
  full_name='SProtoSpace.account_role_data_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.account_role_data_req.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.account_role_data_req.clientid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=98,
)


_ACCOUNT_ROLE_DATA_ACK = _descriptor.Descriptor(
  name='account_role_data_ack',
  full_name='SProtoSpace.account_role_data_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.account_role_data_ack.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.account_role_data_ack.clientid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerid', full_name='SProtoSpace.account_role_data_ack.playerid', index=2,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playername', full_name='SProtoSpace.account_role_data_ack.playername', index=3,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=100,
  serialized_end=196,
)


_GAME_PLAYER_INFO_REQ = _descriptor.Descriptor(
  name='game_player_info_req',
  full_name='SProtoSpace.game_player_info_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.game_player_info_req.clientid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.game_player_info_req.account', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='SProtoSpace.game_player_info_req.game_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=198,
  serialized_end=272,
)


_GAME_PLAYER_INFO_ACK = _descriptor.Descriptor(
  name='game_player_info_ack',
  full_name='SProtoSpace.game_player_info_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.game_player_info_ack.clientid', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.game_player_info_ack.account', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='SProtoSpace.game_player_info_ack.game_id', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playerid', full_name='SProtoSpace.game_player_info_ack.playerid', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playername', full_name='SProtoSpace.game_player_info_ack.playername', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bcanignore', full_name='SProtoSpace.game_player_info_ack.bcanignore', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=275,
  serialized_end=407,
)


_DB_ENTER_GAME_REQ = _descriptor.Descriptor(
  name='db_enter_game_req',
  full_name='SProtoSpace.db_enter_game_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SProtoSpace.db_enter_game_req.player_id', index=0,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.db_enter_game_req.account', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.db_enter_game_req.clientid', index=2,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=409,
  serialized_end=482,
)


_DB_ENTER_GAME_ACK = _descriptor.Descriptor(
  name='db_enter_game_ack',
  full_name='SProtoSpace.db_enter_game_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enter_ret', full_name='SProtoSpace.db_enter_game_ack.enter_ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SProtoSpace.db_enter_game_ack.player_id', index=1,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.db_enter_game_ack.clientid', index=2,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='SProtoSpace.db_enter_game_ack.player_name', index=3,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=484,
  serialized_end=580,
)

DESCRIPTOR.message_types_by_name['account_role_data_req'] = _ACCOUNT_ROLE_DATA_REQ
DESCRIPTOR.message_types_by_name['account_role_data_ack'] = _ACCOUNT_ROLE_DATA_ACK
DESCRIPTOR.message_types_by_name['game_player_info_req'] = _GAME_PLAYER_INFO_REQ
DESCRIPTOR.message_types_by_name['game_player_info_ack'] = _GAME_PLAYER_INFO_ACK
DESCRIPTOR.message_types_by_name['db_enter_game_req'] = _DB_ENTER_GAME_REQ
DESCRIPTOR.message_types_by_name['db_enter_game_ack'] = _DB_ENTER_GAME_ACK

class account_role_data_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_ROLE_DATA_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.account_role_data_req)

class account_role_data_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACCOUNT_ROLE_DATA_ACK

  # @@protoc_insertion_point(class_scope:SProtoSpace.account_role_data_ack)

class game_player_info_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAME_PLAYER_INFO_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.game_player_info_req)

class game_player_info_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAME_PLAYER_INFO_ACK

  # @@protoc_insertion_point(class_scope:SProtoSpace.game_player_info_ack)

class db_enter_game_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DB_ENTER_GAME_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.db_enter_game_req)

class db_enter_game_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DB_ENTER_GAME_ACK

  # @@protoc_insertion_point(class_scope:SProtoSpace.db_enter_game_ack)


# @@protoc_insertion_point(module_scope)
