# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ls_center.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ls_center.proto',
  package='SProtoSpace',
  serialized_pb='\n\x0fls_center.proto\x12\x0bSProtoSpace\x1a\nbase.proto\"2\n\rarea_list_req\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08\x63lientid\x18\x02 \x02(\r\"\xe9\x01\n\rarea_list_ack\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x02(\t\x12\x10\n\x08\x63lientid\x18\x02 \x02(\r\x12*\n\x06groups\x18\x03 \x03(\x0b\x32\x1a.SProtoSpace.gate_net_info\x12\x10\n\x08\x63\x65nterid\x18\x04 \x01(\x04\x12\x31\n\x0b\x61rea_groups\x18\x05 \x03(\x0b\x32\x1c.SProtoSpace.group_area_info\x12\x35\n\x0frecommend_areas\x18\x06 \x03(\x0b\x32\x1c.SProtoSpace.group_area_info\x12\r\n\x05token\x18\x07 \x02(\x05*5\n\x07\x65PropId\x12\x14\n\x10\x61rea_list_req_id\x10\x01\x12\x14\n\x10\x61rea_list_ack_id\x10\x02')

_EPROPID = _descriptor.EnumDescriptor(
  name='ePropId',
  full_name='SProtoSpace.ePropId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='area_list_req_id', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='area_list_ack_id', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=332,
  serialized_end=385,
)

ePropId = enum_type_wrapper.EnumTypeWrapper(_EPROPID)
area_list_req_id = 1
area_list_ack_id = 2



_AREA_LIST_REQ = _descriptor.Descriptor(
  name='area_list_req',
  full_name='SProtoSpace.area_list_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.area_list_req.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.area_list_req.clientid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=94,
)


_AREA_LIST_ACK = _descriptor.Descriptor(
  name='area_list_ack',
  full_name='SProtoSpace.area_list_ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='SProtoSpace.area_list_ack.account', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='SProtoSpace.area_list_ack.clientid', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='groups', full_name='SProtoSpace.area_list_ack.groups', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='centerid', full_name='SProtoSpace.area_list_ack.centerid', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='area_groups', full_name='SProtoSpace.area_list_ack.area_groups', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recommend_areas', full_name='SProtoSpace.area_list_ack.recommend_areas', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='SProtoSpace.area_list_ack.token', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=330,
)

_AREA_LIST_ACK.fields_by_name['groups'].message_type = base_pb2._GATE_NET_INFO
_AREA_LIST_ACK.fields_by_name['area_groups'].message_type = base_pb2._GROUP_AREA_INFO
_AREA_LIST_ACK.fields_by_name['recommend_areas'].message_type = base_pb2._GROUP_AREA_INFO
DESCRIPTOR.message_types_by_name['area_list_req'] = _AREA_LIST_REQ
DESCRIPTOR.message_types_by_name['area_list_ack'] = _AREA_LIST_ACK

class area_list_req(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AREA_LIST_REQ

  # @@protoc_insertion_point(class_scope:SProtoSpace.area_list_req)

class area_list_ack(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AREA_LIST_ACK

  # @@protoc_insertion_point(class_scope:SProtoSpace.area_list_ack)


# @@protoc_insertion_point(module_scope)
