# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mail.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mail.proto',
  package='SProtoSpace',
  serialized_pb='\n\nmail.proto\x12\x0bSProtoSpace\x1a\nbase.proto*\x80\x02\n\x10\x65GS_MAIL_ProtoId\x12\x1a\n\x16ms_gs_mail_send_req_id\x10\x03\x12\x1a\n\x16ms_gs_mail_send_ack_id\x10\x04\x12\x19\n\x15ms_gs_mail_has_req_id\x10\x05\x12\x19\n\x15ms_gs_mail_has_ack_id\x10\x06\x12 \n\x1cms_gs_mail_get_attach_req_id\x10\x07\x12 \n\x1cms_gs_mail_get_attach_ack_id\x10\x08\x12\x1c\n\x18ms_gs_mail_update_req_id\x10\t\x12\x1c\n\x18ms_gs_mail_update_ack_id\x10\n')

_EGS_MAIL_PROTOID = _descriptor.EnumDescriptor(
  name='eGS_MAIL_ProtoId',
  full_name='SProtoSpace.eGS_MAIL_ProtoId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_send_req_id', index=0, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_send_ack_id', index=1, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_has_req_id', index=2, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_has_ack_id', index=3, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_get_attach_req_id', index=4, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_get_attach_ack_id', index=5, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_update_req_id', index=6, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ms_gs_mail_update_ack_id', index=7, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=40,
  serialized_end=296,
)

eGS_MAIL_ProtoId = enum_type_wrapper.EnumTypeWrapper(_EGS_MAIL_PROTOID)
ms_gs_mail_send_req_id = 3
ms_gs_mail_send_ack_id = 4
ms_gs_mail_has_req_id = 5
ms_gs_mail_has_ack_id = 6
ms_gs_mail_get_attach_req_id = 7
ms_gs_mail_get_attach_ack_id = 8
ms_gs_mail_update_req_id = 9
ms_gs_mail_update_ack_id = 10




# @@protoc_insertion_point(module_scope)
